Тестовое задание на должность Frontend-Junior
idbolshakov/apress-frontend_test_task pull request #13
Opened 2019-10-03 18:15 UTC by LazarBergman

Здравствуйте! Меня зовут Кирилл Челиков. Отправляю тестовое задание на должность Frontend-Junior.

2019-10-10 22:29 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ. По ходу проверки возникли следующие вопросы:

1. попап добавления в корзину выглядит не совсем так требует макет (по расположению)

2. попап заказа в хроме едет и выглядит некорректно

3. цена товара без идентификатора валюты

4. js-код у тебя будет выполняться сразу при загрузке страницы и влиять на скорость полной загрузки страницы. Правильнее бы его вынести за какой-нибудь window.onload

2019-10-10 22:29 UTC, idbolshakov commented on src/index.html
> +    <img width="200" height="200" src="assets/images/2.jpg" id="popup-image">
зачем тут заранее указан какой-то товар?

2019-10-10 22:29 UTC, idbolshakov commented on src/index.html
> +    <div id="popupperOne">
почему выбрал такие названия попапов? Почему не `order-popup` и `cart-popup` а какие-то странные схемы именования с One и тд ?)

2019-10-10 22:29 UTC, idbolshakov commented on src/styles.css
> +main {
использовать в качестве ксс-селекторов элементы и айдишники вместо классов - плохая практика

2019-10-10 22:29 UTC, idbolshakov commented on src/api/products.js
> +function hidePopUp() {
у тебя две функции по сути дублируют друг друга `hidePopUp` и `hidePopUpOne`. Как считаешь, можно ли от них отказаться и сделать одну функцию `hidePopup` ?

2019-10-10 22:29 UTC, idbolshakov commented on src/api/products.js
> +  console.log(popupImage)
это зачем?

2019-10-10 22:29 UTC, idbolshakov commented on src/api/products.js
> +  let sectionId = e.target.parentNode.id - 1
почему где-то у тебя const а где-то let? Чем руководствовался когда выбирал `const` или `let` при задании переменной?

из того что я вижу, конкретно с `let` у тебя напутано)

2019-10-10 22:29 UTC, idbolshakov commented on src/api/products.js
> +section.setAttribute("id", item["id"]);
как-то отступы поехали, читать неудобно

2019-10-10 22:29 UTC, idbolshakov commented on src/api/products.js
> +let image = new Image(200, 200)
зачем создавать изображение таким образом, а не просто вставить через `insertAdjacentHTML` ?

2019-10-11 03:51 UTC, LazarBergman commented
Только сейчас заметил, что попап заказа ломается при невысоком разрешении экрана. Я не очень удачно его сверстал, но сейчас знаю, как исправить.
Валюты забыл.
Про скорость загрузки не знал, учту. 
Товары заранее указывал, чтобы посмотреть как примерно будет выглядеть. Потом решил не удалять.
Функции да, можно сделать одну.
Возможно, что я ошибаюсь, но переменные, которые с let, создаются внутри циклов и их значение меняется в зависимости от того, какой попап нужно сформировать. Поэтому я выбрал let.
Изображение с атрибутом-переменной я не смог нормально вставить через insertAdjacentHTML поэтому делал вручную. 
Нужно ли исправлять ошибки и высылать заново?

2019-10-11 12:45 UTC, idbolshakov commented
если есть время, можешь поправить)

2019-10-14 17:57 UTC, LazarBergman commented
Поправил верстку, теперь заказ не разваливается + немного поменял код, чтобы он меньше вопросов вызывал.

2019-10-19 10:42 UTC, merged