Test-Apress
idbolshakov/apress-frontend_test_task pull request #16
Opened 2019-10-13 13:16 UTC by Saymell

Добрый день, благодарю за предоставленное тестовое задание. Старался сделать все в соответствии с ТЗ. Буду рад получить обратную связь. Хочется расти и улучшать свои навыки, конструктивная критика и рекомендации были бы очень полезны для меня)

2019-10-19 10:54 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ.

по соответствию макетам - все ок

по коду есть несколько вопросов и рекомендаций)

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/main.js
> +    for (let i = 0; i < btn.length; i++) {
для таких вещей лучше использовать `forEach` =>

```
btn.forEach(button => ...
```

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/main.js
> +    let btn = document.querySelectorAll('[data-type]');
надо понимать различия let и const и использовать их правильно

let - когда переменная меняет свое значение
const - во всех остальных случаях

у тебя тут почти везде можно и нужно сделать  const

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/main.js
> +        btn[i].addEventListener('click', function () {
навешивать отдельный обработчик `onclick` на все кнопки - неэффективно)

лучше навешать 1 onclick обработчик на какой-то общий контейнер, а в начале проверять на то, что клик был действительно по этой кнопке, вот пример:

```
document.querySelector('.buttons-wrapper').addEventListener('click', event => {
  if (!event.target.classList.contains('.js-button-identity-class-name')) return;

  // обработка клика по кнопке
});

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/main.js
> +            switch (true) {
это вообще что за конструкция такая?) и для чего она тут?

по-моему тут все очень переусложнено

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/modal.js
> +function Modal(type) {
с одной стороны используешь es6+ синтаксис ( в частности для определения переменных), а с другой стороны конструкторы классов описываешь через функциональный стиль, когда можно через class

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/modal.js
> +    this.addInfo = function () {
такие вещи нужно делать через `prototype`

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/modal.js
> +        document.querySelector('.modal-' + this.type + '__title').innerHTML = API.products[productNumber].title;
очень неэффективно все это выглядит

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/modal.js
> +        document.querySelector('.modal-' + this.type + '__title').innerHTML = API.products[productNumber].title;
`'.modal-' + this.type` дублируетя 4 раза

2019-10-19 10:54 UTC, idbolshakov commented on src/api/products/template.js
> +    for (let key in API.products) {
API.products.forEach

2019-10-19 14:40 UTC, Saymell commented on src/api/products/main.js
> +    for (let i = 0; i < btn.length; i++) {
Насколько знаю стрелочные функции не поддерживаются IE 11. На счёт forEach соглашусь, пожалуй это более элегантный перебор. Нужно приучить себя к нему)

2019-10-19 14:42 UTC, Saymell commented on src/api/products/main.js
> +    let btn = document.querySelectorAll('[data-type]');
Привык использовать let, во всех случаях, когда нет прямой необходимости ограничить изменение переменной. Но думаю использовать обратный подход все же эффективнее. Постараюсь учесть это.

2019-10-19 14:50 UTC, Saymell commented on src/api/products/main.js
> +        btn[i].addEventListener('click', function () {
Про это не задумывался, действительно звучит разумнее.

2019-10-19 14:51 UTC, Saymell commented on src/api/products/modal.js
> +function Modal(type) {
Не все технологии ES 6 поддерживаются  IE 11 поэтому пришлось совмещать.

2019-10-19 14:53 UTC, Saymell commented on src/api/products/modal.js
> +    this.addInfo = function () {
Задумывался об этом, но почему-то не реализовал)

2019-10-19 14:54 UTC, Saymell commented on src/api/products/modal.js
> +        document.querySelector('.modal-' + this.type + '__title').innerHTML = API.products[productNumber].title;
Тоже бросалось это в глаза, но не придумал как сделать лучше.

2019-10-19 14:56 UTC, Saymell commented
Спасибо за обратную связь. Теперь есть о чем задуматься. Постараюсь в ближайшее время провести работу над ошибками. Если вы не против ещё раз провести ревью)

2019-10-19 14:58 UTC, Saymell commented on src/api/products/main.js
> +            switch (true) {
Лучше разделить на отдельные функции?

2019-10-20 22:25 UTC, Saymell commented
Change log:
1. Изменил все циклы на forEach
2. Заменил let на const, там где это было необходимо
3. Перенес методы класса в prototype
4. Изменил логику добавления модальных окон
5. Поменял обработчик события onclick

2019-10-21 15:23 UTC, idbolshakov commented on src/api/products/main.js
> +            switch (true) {
для чего тут вообще Switch ?  какую задачу он выполняет?

2019-12-25 12:19 UTC, closed without merging