Frotend test, Eremin M.V.
idbolshakov/apress-frontend_test_task pull request #24
Opened 2019-11-20 18:12 UTC by enflaer

Немного расширил функционал того, что просили, добавив сервер, чтобы можно было потестить и немного сменил файл с апи на json, чтобы корректно получать данные из него. Надеюсь ничего страшного. В остальном реализация по тз.

npm run dev - сборка проекта на локальный сервер для теста.

2019-11-21 06:32 UTC, enflaer commented
В ТЗ было `Фреймворки, библиотеки, шаблонизаторы использовать нельзя - чистый js и css`, вебпак - бандлер, а бабель - компилятор, думаю, что это не помешает проверке задания? Но если необходимо, могу переписать всё без них, если необходимо.

2019-11-21 06:44 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ)

да, нужно переписать в соответствии с ТЗ без дополнительного функционала и библиотек)

2019-11-21 12:50 UTC, enflaer commented
@idbolshakov, надеюсь, полифиллы не запрещены? Или тоже убрать? Если можно, то жду ревью)

2019-11-26 18:41 UTC, idbolshakov requested changes
привет, спасибо за внесение правок и выполнение ТЗ в соответствии с требованиями)

замечания к верстке:

1. если проскроллить список товаров вниз и добавить какой-то товар в корзину, то попап добавления в корзину будет не виден во вью-порте пользователя

и по коду есть несколько вопросов

2019-11-26 18:41 UTC, idbolshakov commented on src/assets/images/close-gray.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
svg нужно жать) например тут https://jakearchibald.github.io/svgomg/

2019-11-26 18:41 UTC, idbolshakov commented on src/css/main.css
> +/*
не совсем понял зачем тут данный коммент?)

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +  (function () {
зачем еще обертка?

2019-11-26 18:41 UTC, idbolshakov commented on .gitignore
> +/node_modules
ненужные для этого решения игноры)

2019-11-26 18:41 UTC, idbolshakov commented on src/css/main.css
> +.cart-popup.opened {
какая система именования классов использовалась?)

в общем и целом похоже на БЭМ, но местами как бы и не БЭМ, это немного сбивает с толку

+ если все таки это БЭМ, то почему решил все сложить в 1 файл а не разбить по блокам?

2019-11-26 18:41 UTC, idbolshakov commented on src/index.html
> +      <a href="#" class="cart-popup__goToCart btn btn--primary btn--high btn--wide">Перейти в корзину</a>
для таких вещей лучше использовать тег `button` стилизованный под ссылку

2019-11-26 18:41 UTC, idbolshakov commented on src/index.html
> +      <label for="orderPopup-phone">Ваш телефон*:</label>
кажется, что тут можно было просто в label положить input и отказаться от лишних атрибутов

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +    if (navigator.userAgent.indexOf('MSIE') !== -1
полифиллы это ок, но почему положил их в один и тот же файл, что и бизнес-логику?

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +          '    <a href="javascript:" class="btn btn--primary product-buttons__order">Заказать</a>' +
это плохая практика

лучше использовать `button`

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +        goodsPlace.insertAdjacentHTML('beforeEnd',
10 раз вставляешь в DOM кусок html,

не очень эффективно, лучше сложить все в переменную и вставить 1 раз

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +    function addToCart() {
какая-то очень перегруженная реализация)

почему нельзя повешать 1 обработчик на общий контейнер всех этих кнопок? и проверять при клике, что была кликнута именно кнопка "добавить в корзину" ?

у тебя же получается что сколько товаров, столько и обработчиков) да еще и какие-то сложные преобразования и манипуляции с DOMом

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +    function addToCart() {
название функции не соответствует тому, что в ней делается и комментарию к этой функции)

лучше дать более понятное имя и отказаться от комментария

2019-11-26 18:41 UTC, idbolshakov commented on src/js/index.js
> +    function removeFromCart() {
и тут тоже самое, очень перегруженная и сложная реализация, куча ненужных манипуляций с домом)

2019-11-27 13:05 UTC, enflaer commented
@idbolshakov Учёл замечания и постарался поправить места где всё было не очень хорошо.

2019-11-27 13:06 UTC, enflaer commented on src/css/main.css
> +/*
Изначально начал использовать переменные, а потом увидел, что ие11 не может в них. Закомментил, чтобы были под рукой.

2019-12-05 05:51 UTC, closed without merging