Тестовое задание
idbolshakov/apress-frontend_test_task pull request #25
Opened 2019-11-21 22:44 UTC by XCanG

Хлопотов Александр

2019-11-25 14:28 UTC, XCanG commented
Задание не проверяли ещё?

2019-11-26 19:02 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ

замечания к реализации:

1. попап добавления товара в корзину вообще не такой как нужен в макете

и по коду есть вопросы:

2019-11-26 19:02 UTC, idbolshakov commented on src/assets/styles.css
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans&display=swap');
а если по какой-то причине `fonts.googleapis.com` будет недоступен? как это повлияет на работоспособность твоего решения?

2019-11-26 19:02 UTC, idbolshakov commented on src/assets/styles.css
> +body {
почему решил сложить все стили в один файл?

такое решение в дальнейшем будет сложно поддерживать

2019-11-26 19:02 UTC, idbolshakov commented on src/assets/styles.css
> +	background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iNTEycHgiIHdpZHRoPSI1MTJweCIgdmlld0JveD0iMCAtMzEgNTEyLjAwMDI2IDUxMiI+PHBhdGggZmlsbD0iI2IwMjE1
почему решил все иконки сложить в base64 ?

2019-11-26 19:02 UTC, idbolshakov commented on src/index.html
> +					<div class="checkout" tabindex="0">Перейти в корзину</div>
для кликабельных элементов лучше использовать `button` или `a`

2019-11-26 19:02 UTC, idbolshakov commented on src/assets/styles.css
> +body {
например, все полифиллы ты вынес в отдельный файл, а почему нормализацию стилей оставил в одном файле с селекторами бизнес-логики?

2019-11-26 19:02 UTC, idbolshakov commented on src/api/products.js
> +var cart = document.querySelector(".nav .cart"),
хорошо бы работу js-a выносить за обработчик window.onload или подобный, чтобы не тормозить загрузку страницы

2019-11-26 19:02 UTC, idbolshakov commented on src/api/products.js
> +	let len = Object.keys(cart_data).length,
какое-то неинформативное название переменной

почему через `let` ?

2019-11-26 19:02 UTC, idbolshakov commented on src/api/products.js
> +if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
это вообще что за магия?))

2019-11-26 19:02 UTC, idbolshakov commented on src/api/products.js
> +const render_products = function(response) {
очень перегруженная реализация сложная в поддержке

представь, что нужно будет измзенить структуру блока товара? или добавить новый элемент или атрибут?

для такого лучше использовать `innerHTML` или `insertAdjacentHTML`

2019-11-26 19:02 UTC, idbolshakov commented on src/api/products.js
> +		checkout.addEventListener("click", quick_checkout, false);
у тебя на каждый элемент создается свой обработчик события - это неэффективно

нужно вешать  1 обработчик на общий контейнер товаров и проверять, действительно ли был клик на кнопку заказа

2019-11-27 03:58 UTC, XCanG commented on src/assets/styles.css
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans&display=swap');
Шрифты с CDN гугла имеют 100% Uptime, однако можно сохранить их в локальное хранилище и подгружать с сайта. Но преимущества этого метода в том, что ссылки на шрифты одинаковы и если пользователь уже закешировал этот шрифт, то ему не придётся повторно его перекачивать, к тому же скорость отклика у их серверов очень быстрая.

2019-11-27 04:02 UTC, XCanG commented on src/assets/styles.css
> +body {
Ну в ТЗ не было никакой информации по другим компонентам сайта, а так же необходимостью соблюдения каких-то других правил. Поскольку заданием была лишь одна проверочная страница, я не стал усложнять решение нагромождением данных. Тоже и касается JS.

2019-11-27 04:03 UTC, XCanG commented on src/assets/styles.css
> +	background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iNTEycHgiIHdpZHRoPSI1MTJweCIgdmlld0JveD0iMCAtMzEgNTEyLjAwMDI2IDUxMiI+PHBhdGggZmlsbD0iI2IwMjE1
Как написал выше, я упростил решение. Сами иконки могут быть выложены в ассеты и вместо base64 указать на них ссылкой.

2019-11-27 04:17 UTC, XCanG commented on src/api/products.js
> +var cart = document.querySelector(".nav .cart"),
Я использую новое решение. Скрипт у меня не блокирует загрузку страницы, а подгружается асинхронно, к тому же были проведены тесты Lighthouse, которые показали высокую оценку производительности.
Про асинхронную подгрузку можно почитать тут: https://developers.google.com/web/tools/lighthouse/audits/blocking-resources
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript

2019-11-27 04:19 UTC, XCanG commented on src/api/products.js
> +	let len = Object.keys(cart_data).length,
cart_data = данные из корзины
let потому что необходимо ограничить область видимости переменной. Использование var приводит к нежелательным последствиям.

2019-11-27 04:21 UTC, XCanG commented on src/api/products.js
> +if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
Это не магия, а проверка юзер-агента (в данном случае IE11) и исправление проблем с совместимостью в старом браузере. В Edge, Firefox, Chrome, Opera всё остальное работает без проблем и эта часть кода там не нужна.

Только потому что в ТЗ была поддержка IE11.

2019-11-27 04:25 UTC, XCanG commented on src/api/products.js
> +const render_products = function(response) {
Сам код не перегруженый, но репетативный, однако работает быстро. Можно, конечно, использовать `insertAdjacentHTML`, но с `innerHTML` сложнее работать и навешивать event listener'ы и он работает медленнее.

2019-11-27 04:28 UTC, XCanG commented on src/api/products.js
> +		checkout.addEventListener("click", quick_checkout, false);
Можно проверять и одним событием. Расчёт был в пределах 25 товарах на странице, поэтому и события добавлялись исключительно на само события и не добавлялась промежуточная функция проверки. Сама функция тоже негативно влияет на производительность, особенно когда на сайте много интерактивных элементов и все работают глобально на странице. Если элементов действительно много, то замена на единственный слушатель будет наоборот более эффективной.

2019-11-27 04:29 UTC, XCanG commented
@idbolshakov ответил на возникшие вопросы.

2019-11-27 06:48 UTC, XCanG commented
Заменил способ вставки на `insertAdjacentHTML` и event listener'ы на глобальные с проверкой элемента.

2019-11-27 10:44 UTC, idbolshakov commented on src/assets/styles.css
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans&display=swap');
ничего и никогда не имеет 100% аптайм)

точно также как нет вечного двигателя, поэтому такие вещи стоит учитывать

2019-11-27 10:44 UTC, idbolshakov commented on src/assets/styles.css
> +body {
тогда почему полифиллы лежат отдельно а все остальное свалено в кучу?)

2019-11-27 10:44 UTC, idbolshakov commented on src/assets/styles.css
> +	background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iNTEycHgiIHdpZHRoPSI1MTJweCIgdmlld0JveD0iMCAtMzEgNTEyLjAwMDI2IDUxMiI+PHBhdGggZmlsbD0iI2IwMjE1
а почему ты решил упростить решение?)

2019-11-27 10:49 UTC, idbolshakov commented on src/api/products.js
> +var cart = document.querySelector(".nav .cart"),
от того, что оно выполняется асинхронно не значит, что оно не тормозит загрузку страницы)

событие window.onload не всплывет, до тех пор, пока не отработает скрипт

2019-11-27 10:50 UTC, idbolshakov commented on src/api/products.js
> +	let len = Object.keys(cart_data).length,
к каким последствиям приводит использование var ?  И что значит "ограничить область видимости переменной"  в твоем случае? Из того что я вижу - в этом случае вообще не важно испоьзовать let или var

но я имел в виду, почему let, когда тут нужен const ?

2019-11-27 10:51 UTC, idbolshakov commented on src/api/products.js
> +if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
очень надеюсь, что через пол года ты вспомнишь что это и зачем)

2019-11-27 10:51 UTC, idbolshakov commented on src/api/products.js
> +const render_products = function(response) {
event listener'ы не надо навешивать постоянно, оно делается 1 раз

2019-11-27 10:56 UTC, idbolshakov commented on src/api/products.js
> +		checkout.addEventListener("click", quick_checkout, false);
очень плохо, что ты не понимааешь, что 25 одинаковых event listener'ов хуже чем 1 event listener с проверкой условия)

https://learn.javascript.ru/event-delegation  вот, можешь почитать)

2019-11-27 10:57 UTC, idbolshakov commented on src/api/products.js
> +if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
такие вещи нужно комментировать или давать понятные имена переменным, чтобы другие люди или ты сам через пол года понимал что это и зачем

2019-11-27 10:59 UTC, idbolshakov requested changes

2019-11-27 10:59 UTC, idbolshakov commented on src/api/products.js
> +	let t = e.target;
ты понимаешь различия let, const и var ?) и когда что нужно использовать?)

2019-11-27 11:07 UTC, idbolshakov commented on src/api/products.js
> +	let len = Object.keys(cart_data).length,
и про неинформативное имя переменной я имел в виду `len`

2019-11-27 11:59 UTC, XCanG commented on src/api/products.js
> +	let t = e.target;
Да. `var` объявляется в глобальной области видимости, которая также присваивается к `window["имя_переменной"]`, за исключением экранирования в функции:
```js
(function () {
   var private_variable;
})();
```
`let` объявляется в локальной области видимости, только внутри функции или оператора (например, циклов) и не распространяется на другие функции. Также `let` и `const` нельзя вызвать до их объявления, что приведёт к выводу ошибки, тогда как `var` будет неопределён `undefined`.

`const` похож на `let`, за тем исключением, что после назначения переменной, её нельзя будет переназначить, это приведёт к ошибке.

Использование `let` или `const` предотвратит ошибки изменения переменных, которые могли были быть назначены в других скриптах или в других функциях в пределах того же скрипта.

2019-11-27 12:21 UTC, idbolshakov commented on src/api/products.js
> +	let t = e.target;
Есть хорошая практика - использовать const всегда когда это возможно а let в остальных случаях

У тебя же хаотично все это и выглядит так, как будто ты не понимаешь для чего оно нужно

2019-11-27 12:22 UTC, idbolshakov commented on src/api/products.js
> +	let t = e.target;
Все намного проще var объявляет переменную в области видимости функции или глобально а const и let в области видимости блока или глобально

2019-12-25 12:18 UTC, closed without merging