Тестовое задание. Кондрев Георгий Андреевич.
idbolshakov/apress-frontend_test_task pull request #27
Opened 2019-12-01 18:40 UTC by FrontEndJun

2019-12-03 02:18 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ, но это немного не то.

нужно было выполнить задание без использования сторонних библиотек и фреймворков на чистом js, css, html

т.е. всякие сборщики, бабели, преттиеры и прочее использовать было нельзя.

2019-12-03 02:18 UTC, idbolshakov commented on src/assets/js/helpers.js
> +    if (key.startsWith("data-")) {
а что тут простой `indexOf` не подошел бы?)

2019-12-03 02:18 UTC, idbolshakov commented on src/assets/js/main.js
> +function createProductItem(item) {
очень сложный императивный код

все намного проще и декларативней можно было сделать через `innerHTML` или `insertAdjacentHTML`

к тому же в поддержке твоя реализация будет очень сложна. Представь, что нужно будет через пол года добавить какой-то атрибут, тег, изменить структуру и пр. в этом коде нужно будет долго разбираться

2019-12-03 02:18 UTC, idbolshakov commented on src/assets/js/main.js
> +  window: document.querySelector(".modal"),
почему такое название? очень легко спутать с глобальным объектом `window`

2019-12-03 02:18 UTC, idbolshakov commented on src/index.html
> +      <a href="#" class="cart__button button button--main">Перейти в корзину</a>
для таких вещей лучше использовать `<button>`

2019-12-03 02:18 UTC, idbolshakov commented on src/assets/scss/blocks/button.scss
> +.button {
то что используешь БЭМ - хорошо,

2019-12-03 02:18 UTC, idbolshakov commented on src/assets/js/main.js
> +  document.querySelector(".product-list").appendChild(product);
на каждую итерацию новая вставка в DOM. Гораздо эффективнее вставить в DOM 1 раз результат всех итераций

2019-12-03 02:18 UTC, idbolshakov commented
самый большой вопрос - при открытии index.html в папке dist  не вижу решения

2019-12-03 02:33 UTC, FrontEndJun commented
Там же вебпак. 
Напишите в консоли  npm run dev

2019-12-03 02:37 UTC, FrontEndJun commented
Или я сегодня вечером посмотрю в чем проблема и запущу изменения

2019-12-03 02:47 UTC, idbolshakov commented
данное ТЗ вообще не предполагало использование каких либо зависимостей и сторонних библиотек в том числе вебпака. Поэтому при проверке предполагается что нужно просто открыть index.html и все заработает. Без дополнительных манипуляций.


но даже если проигнорировать это, то папка dist и build предполагают, что в них должно находится готовое к проверке решение.

2019-12-03 02:50 UTC, FrontEndJun commented
Ок.
В ТЗ указано не использовать библиотеки, про Бандеры, таскраннеры нет ни слова.

2019-12-03 02:51 UTC, FrontEndJun commented
Но я вас понял

2019-12-04 06:47 UTC, FrontEndJun commented
Здравствуйте, поправил решение и запуск проекта

2019-12-25 12:18 UTC, closed without merging