ready!!!
idbolshakov/apress-frontend_test_task pull request #30
Opened 2020-01-10 21:52 UTC by A-S-Varlamov

2020-01-12 21:03 UTC, idbolshakov requested changes
Привет, спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. В chromium изображения товаров в листинге как-то обрезаются, особенно видно на предпоследнем товаре

2. Зачем под индексацией гита конфиг .idea ?

3. Почему для иконок используешь png а не svg?

2020-01-12 21:03 UTC, idbolshakov commented on src/index.html
> +    <div id="cover" hidden onclick="hiddenPopup()"></div>
инлайн обработчики в html - плохая практика

2020-01-12 21:03 UTC, idbolshakov commented on src/script.js
> +        getElement("productList").appendChild(div);
получается, что ты каждый товар отдельно в DOM вставляешь. Это не очень эффективно. Есть идеи, как это улучшить?

2020-01-12 21:03 UTC, idbolshakov commented on src/script.js
> +        const div = createElement('product');
а зачем тут отдельно создавать div, а ниже в него вставлять содержимое через innerHTML ?

2020-01-12 21:03 UTC, idbolshakov commented on src/script.js
> +    return document.getElementById(str);
для чего это выносить в отдельную функцию?

2020-01-12 21:03 UTC, idbolshakov commented on src/script.js
> +    const popup = getElement("popupCart");
при каждом клике у тебя происходит обращение к DOM и поиск одного и того же элемента. Есть идеи, как это улучшить?

2020-01-12 21:03 UTC, idbolshakov commented on src/style.css
> +    font-family: Arial, Helvetica, sans-serif;
кажется, использовать Arial как основной шрифт - не очень крутая идея

2020-01-12 21:03 UTC, idbolshakov commented on src/style.css
> +.product [name="inCart"] {
почему решил использовать такие сложные селекторы?

2020-01-13 05:27 UTC, A-S-Varlamov commented
Привет. Что-то я поторопился и получилось все не очень эффективно. Сейчас все переделаю!

2020-01-13 05:47 UTC, A-S-Varlamov commented on src/index.html
> +    <div id="cover" hidden onclick="hiddenPopup()"></div>
ага, надо делать через addEventListener

2020-01-13 05:48 UTC, A-S-Varlamov commented on src/script.js
> +        getElement("productList").appendChild(div);
Собираем список в фрагмент, а потом вставляем в дом

2020-01-13 05:53 UTC, A-S-Varlamov commented on src/script.js
> +    return document.getElementById(str);
функции читаются проще да и писанины меньше.

2020-01-13 08:45 UTC, A-S-Varlamov commented
Все исправил!

2020-01-20 11:50 UTC, closed without merging