Добавлены вывод списка товаров, обработка кнопок заказать, в корзину
idbolshakov/apress-frontend_test_task pull request #35
Opened 2020-01-19 11:48 UTC by endiko

Выполненное тестовое задание от Когай Надежды

2020-01-20 11:21 UTC, idbolshakov requested changes
Привет, спасибо за выполнение ТЗ. Видно, что у тебя есть хорошее понимание базовых технологий веба, это очень круто. К решению есть несколько вопросов.

2020-01-20 11:21 UTC, idbolshakov commented on src/index.html
> +  <link
Видишь ли ты какие-то недостатки данного решения - использовать гугл-шрифты ?

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +const getTargetProduct = (index, products) => products.filter(product => parseInt(product.id) === parseInt(index))[0];
не совсем понял зачем такая функция нужна.  `Api.products[index]`  не решает ту же задачу?

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +const createProductItem = (productData) => (
Кажется, что комментарий функции и название функции немного разный смысл имеют.

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +            <img src="${productData.img}" class="product__img" />
чтобы прям совсем хорошо, наверное еще можно добавить `alt`

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +        <button class="btn order-btn" name="order" data-index="${productData.id}">Заказать</button>
а тут бы `type="button"`

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +    let productsContainer = document.createElement('ul');
почему `let` ?

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +    return productsContainer;
вообще не понятно зачем тут смешивать и создание DOM элемента через `createElement` и последующую вставку  в него html в виде строки через `insertAdjacentHTML`, а потом ты еще результат данной функции вставляешь в DOM через appendChild. Как-то перегружено и смешанно.


Кажется, что проще было на всех этапах генерить строку html и вставлять на страницу через insertAdjacentHTML, сэкономили бы несколько строчек и код бы стал явно понятнее

2020-01-20 11:21 UTC, idbolshakov commented on src/index.js
> +const renderPopup = async (type, index, data) => {
кажется, что для данного ТЗ не совсем корректно и оправдано использовать  async await, так как по условию данные доступны сразу.

2020-01-20 16:20 UTC, endiko commented on src/index.html
> +  <link
Насколько я правильно поняла вопрос - смутил способ подключения шрифтов через CDN.
На самом деле, подключение через CDN обычно не рекомендуется, потому что может получиться такая ситуация, что CDN станет вдруг недоступным и подключенные шрифты тоже станут недоступными. Использование CDN в целом, может сказаться на скорости загрузки сайта. Лучшим способом считается подключение шрифтов локально через css свойство @font-face.
Что касается тестового задании, то я подключила их через CDN, потому что так было быстрее и проще, да и в самом задании не указывалось каким конкретно способом требуется подключить шрифты)

2020-01-20 16:25 UTC, endiko commented on src/index.js
> +const getTargetProduct = (index, products) => products.filter(product => parseInt(product.id) === parseInt(index))[0];
В данном тестовом задании можно было бы обойтись и без функции getProducts, но мне хотелось сымитировать работу получения данных через API

2020-01-20 16:39 UTC, endiko commented on src/index.js
> +const createProductItem = (productData) => (
Согласна, выглядит немного странно))) 
Я и сейчас почему-то затрудняюсь придумать правильное описание...
Функция createProductItem создает товар по входным данным и возвращает строку, содержащую html код товара

2020-01-20 16:39 UTC, endiko commented on src/index.js
> +            <img src="${productData.img}" class="product__img" />
Спасибо за замечание) 
Забыла добавить атрибут alt к тегу img

2020-01-20 16:40 UTC, endiko commented on src/index.js
> +        <button class="btn order-btn" name="order" data-index="${productData.id}">Заказать</button>
Согласна

2020-01-20 16:50 UTC, endiko commented on src/index.js
> +    let productsContainer = document.createElement('ul');
Здесь можно объявить и через const и через let. 
Просто привычка - по умолчанию объявлять переменные через let

2020-01-20 17:02 UTC, endiko commented on src/index.js
> +    return productsContainer;
`const createProductsList = (data) => (`<ul class="product__list">${data.map(product => createProductItem(product)).join('')}</ul>`)`

Спасибо за замечание) Действительно, намного сокращает код, не подумала сразу)

2020-01-20 17:20 UTC, endiko commented on src/index.js
> +const renderPopup = async (type, index, data) => {
Для данного тестового - да, но в реальности данные обычно доступны не сразу и я подумала, что хорошо было бы обработать наперед такую ситуацию и предотвратить ошибки, которые могли бы возникнуть, в случае, если бы данные не были бы доступны сразу и функции, которым нужны были бы эти данные не смогли получить их и вернули бы ошибки или некорректные данные. 
К тому же, был повод попрактиковать async/await)

2020-01-20 17:26 UTC, idbolshakov commented on src/index.html
> +  <link
ок

2020-01-20 17:26 UTC, idbolshakov commented on src/index.js
> +const getTargetProduct = (index, products) => products.filter(product => parseInt(product.id) === parseInt(index))[0];
почему тебе захотелось так сделать?)

2020-01-20 17:27 UTC, idbolshakov commented on src/index.js
> +const createProductItem = (productData) => (
просто, наверное, иногда ограничиться понятным названием функции без комментария)

2020-01-20 17:28 UTC, idbolshakov commented on src/index.js
> +    let productsContainer = document.createElement('ul');
есть хорошая практика - объявлять const везде где можно, а let - в остальных случаях)

2020-01-21 06:25 UTC, endiko commented on src/index.js
> +const getTargetProduct = (index, products) => products.filter(product => parseInt(product.id) === parseInt(index))[0];
Для приближения условий к реальной жизни, потому что в реальности, если мы получаем данные из какого-либо API, мы обычно пишем функцию получения данных из API. Поэтому мне показалось, что правильнее будет сделать функцию-обертку для получения данных списка товаров из API)

2020-01-21 07:15 UTC, endiko commented on src/index.js
> +    let productsContainer = document.createElement('ul');
Да, я тоже слышала про это.
Плюс const в том, что объявляя переменные через const, мы защищаем их от случайного переопределения напрямую.
Примитивы объявляем через let, если их значения могут измениться в коде (например, переменная для итерации в цикле, логическая переменная, если она меняет свое состояние true/false и тд)
Я стараюсь придерживаться этому правилу, но бывает, что по привычке пишу let.
Исправила на const

2020-01-26 12:05 UTC, closed without merging