'Valentine_Zigmund_task'
idbolshakov/apress-frontend_test_task pull request #37
Opened 2020-01-21 08:30 UTC by ValentineZigmund

2020-01-26 04:00 UTC, idbolshakov requested changes
привет, ТЗ не открывается в браузере, видимо нужно дополнительно какой-то сервер поднимать, а должно все работать из коробки, простым открытием index.html в браузере, также по коду есть несколько вопросов.


 как-то все это выглядит очень неоправданно перегружено)

2020-01-26 04:00 UTC, idbolshakov commented on src/style.css
> +@import url('/common.blocks/main/main.css');
такой способ подключения стилей считается плохой практикой https://stackoverflow.com/questions/6912899/css-import-best-practices

2020-01-26 04:00 UTC, idbolshakov commented on src/index.html
> +        <div class="popup">
а почему решил сложить динамические элементы сразу в контент страницы?

2020-01-26 04:00 UTC, idbolshakov commented on src/index.html
> +                    <button class="close-btn close-btn_close-popup popup__close-btn"></button>
тут действительно нужно столько классов?

2020-01-26 04:00 UTC, idbolshakov commented on src/App.js
> +API.products.forEach(product =>  _io_q('.main-page__list')
выполнять код таким образом - не очень хорошая идея, лучше дожидаться события window.onload или domcontentloaded

2020-01-26 04:00 UTC, idbolshakov commented on src/App.js
> +API.products.forEach(product =>  _io_q('.main-page__list')
вообще не понятно зачем тут с одной стороны усложнять код дополнительными утилитами для кеширования дом элементов (по-моему тут это точно лишнее), но в то же время вызывать appendChild для каждого нового товара.

2020-01-26 04:00 UTC, idbolshakov commented on src/App.js
> +const createListItem = (imgSrc, price, title, id) => {
это очень сложный в поддержке код, представь, что через пол года нужно будет изменить структуру - добавить элемент, удалить, изменить атрибут. Чтобы это сделать, нужно будет сидеть и вникать в это все приличное количество времени)

2020-01-26 04:00 UTC, idbolshakov commented on src/App.js
> +const createBlock = (...args) => {
зачем все это делать?) 

все же просто `innerHTML` или `insertAdjacentHTML` и не надо городить собственных обвязок вокруг DOM api )

сам же через пол года ногу сломишь в этих велосипедах, беречь себя нужно))

2020-01-26 04:00 UTC, idbolshakov commented on src/common.blocks/btn/_order/btn_order.js
> +orderProduct.forEach(elem => elem.onclick = () => {
это все ужасно неэффективно 

https://learn.javascript.ru/event-delegation вот с этим нужно ознакомиться)

ну и вообще учебник хороший)

2020-01-27 09:08 UTC, ValentineZigmund commented on src/style.css
> +@import url('/common.blocks/main/main.css');
Согласен, я бы применил webpack для компоновки всех .css, но дополнительные утилиты нельзя использовать по тз. Более оптимального способа я, увы не находил.

2020-01-27 09:09 UTC, ValentineZigmund commented on src/index.html
> +        <div class="popup">
Я руководствовался тем, что если скрипт слетит, то контент отрисуется частично. Пользователь, возможно сможет выполнить необходимые операции и уведомить об ошибке. Если же весь контент будет рендероть скрипт, то при его отключении пользователь не увидит вообще ничего. В данном конкретном случае это не работает, но в компонентах с более сложной логикой может помочь.

2020-01-27 09:09 UTC, ValentineZigmund commented on src/index.html
> +                    <button class="close-btn close-btn_close-popup popup__close-btn"></button>
Если вопрос касательно кнопки: первый класс задал для основных стилей кнопки, его можно переиспользовать в других блоках. Второй для функционала js именно в этом блоке. Третий это микс для позиционирования относительно других элементов. Если я правильно понимаю методологию БЭМ, то эти селекторы не принято объединять. 
Если вопрос касательно popup: можно объединить селекторы popup и popup__body, но я предпочел сделать именно так, мне кажется, что лаконичнее: основная обертка отвечает за сокрытие фона, а __body уже за сам контент.

2020-01-27 09:09 UTC, ValentineZigmund commented on src/App.js
> +API.products.forEach(product =>  _io_q('.main-page__list')
Принял. Исправил.

2020-01-27 09:10 UTC, ValentineZigmund commented on src/common.blocks/btn/_order/btn_order.js
> +orderProduct.forEach(elem => elem.onclick = () => {
Исправил. Учебником пользуюсь, но конкретно эту тему ещё не разбирал.

2020-01-27 09:12 UTC, ValentineZigmund commented on src/App.js
> +const createBlock = (...args) => {
Согласен, такой легче поддерживается. Исправил.

2020-02-06 10:03 UTC, closed without merging