Тестовое задание на должность фронтенд-разработчика
idbolshakov/apress-frontend_test_task pull request #38
Opened 2020-01-30 08:32 UTC by PatricCormac

Разработал клиентскую часть листинга товаров с попапом заказа и добавления в корзину.

2020-02-03 02:09 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ, визуально все круто, к коду есть несколько вопросов

1. Почему css решил сложить в один файл, а js разбит на два файла? Какой принцип разбиения использовался?

2020-02-03 02:09 UTC, idbolshakov commented on src/popup.js
> +document.addEventListener('keydown',(e)=>{
нет единства офорления кода, тут стрелочная функция без пробелов, сверху с пробелами. Лучше и чище использовать какой-то единый стиль

2020-02-03 02:09 UTC, idbolshakov commented on src/index.html
> +                <div class="button-submit">
если это кнопка, то лучше явно в разметке использовать тег `button` а не стилизованные под кнопку дивы. Семантическая верстка это очень полезно

2020-02-03 02:09 UTC, idbolshakov commented on src/api/products.js
> +for (let i = 0; i < API.products.length; i++) {
хорошая практика - использовать для таких вещей методы `Array.prototype.forEach` и тп вместо циклов

2020-02-03 02:09 UTC, idbolshakov commented on src/api/products.js
> +let wrap = document.querySelector('.product-listing-wrapper');
хорошая практика - откладывать исполнение кода до события `window.onload` или хотя бы `dom content loaded`

2020-02-03 02:09 UTC, idbolshakov commented on src/api/products.js
> +let wrap = document.querySelector('.product-listing-wrapper');
почему используется объявление через `let` ?

2020-02-03 02:09 UTC, idbolshakov commented on src/api/products.js
> +  let cart = document.createElement('div');
а теперь представь, что через пол года кому-то или даже тебе нужно поменять структуру верстки или добавить/удалить атрибут из этого кода.

Очень императивный код для такой задачи. Лучше, быстрее, нагляднее будет использовать `innerHTML` или `insertAdjacentHTML`

2020-02-03 04:27 UTC, PatricCormac commented on src/popup.js
> +document.addEventListener('keydown',(e)=>{
Да, верно.

2020-02-03 04:27 UTC, PatricCormac commented on src/index.html
> +                <div class="button-submit">
Понял, учту в следующий раз.

2020-02-03 04:29 UTC, PatricCormac commented on src/api/products.js
> +for (let i = 0; i < API.products.length; i++) {
Хорошо, попробую такой способ

2020-02-03 04:37 UTC, PatricCormac commented on src/api/products.js
> +let wrap = document.querySelector('.product-listing-wrapper');
Потому что это ES6, а var уже для legacy проектов, к тому же let только в рамках блока виден, в будущем может пригодиться

2020-02-03 04:43 UTC, PatricCormac commented on src/api/products.js
> +  let cart = document.createElement('div');
Да, согласен.
По поводу разбиения js на два файла, делал это руководствуясь тем, что в одном файле будет происходить рендер структуры, а заполнение контентом происходит во втором файле при обработке событий.

2020-02-03 04:52 UTC, idbolshakov commented on src/api/products.js
> +let wrap = document.querySelector('.product-listing-wrapper');
если используешь ES6 то хорошо бы ознакомиться с его особенностями и лучшими практиками. В данном случае надо хоршоо понимать различия между const и let, и в большинстве случаев использовать const, а let только там где это действительно необходимо

2020-02-03 04:52 UTC, idbolshakov commented on src/api/products.js
> +  let cart = document.createElement('div');
а почему тогда стили лежат в одном файле и не разбиты по какому-либо принципу?

2020-02-03 04:56 UTC, PatricCormac commented on src/api/products.js
> +  let cart = document.createElement('div');
Не привык ещё CSS разбивать, но уже пробовал и заметил упрощение редактирования стилей.

2020-02-03 04:57 UTC, PatricCormac commented on src/api/products.js
> +let wrap = document.querySelector('.product-listing-wrapper');
Спасибо, посмотрю по этой теме.

2020-02-05 09:30 UTC, PatricCormac commented
Не смотрел ещё изменения?

2020-02-06 10:02 UTC, closed without merging

2020-02-06 11:13 UTC, idbolshakov commented
не смотрел