Тестовое задание
idbolshakov/apress-frontend_test_task pull request #40
Opened 2020-02-03 13:50 UTC by YaroslavWD

Есть еще много вещей и вариантов реализации которые можно улучшить постарался максимально показать различные подходы и что я умею.

2020-02-03 17:43 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. есть возможность открыть одновременно несколько разных попапов заказа и корзины, что не совсем корректно

2020-02-03 17:43 UTC, idbolshakov commented on src/index.html
> +              <!-- Эталон
это тут зачем?

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +let catalogContainer = document.querySelector(".catalog__inner");
зачем все это в глобальной области видимости?

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +let catalogContainer = document.querySelector(".catalog__inner");
почему let ?

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +let productData = API.products;
зачем это в переменную?

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +const createItem = (elementTemeplate, dataObject) => {
очень сложная и неподдерживаемая реализация, нужно все проще и нагляднее делать через `innerHTML` или `insertAdjacentHTML`

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +generateItem();
код лучше выполнять после `window.onload` или подобного

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +const getElementById = (dataSet, idElement) => {
какая-то излишне сложная конструкция, кажется тут все решается в одноу строчку через API.products.find

2020-02-03 17:43 UTC, idbolshakov commented on src/js/script.js
> +    orderBtn.addEventListener("click", createOrder);
зачем для каждой кнопки регистрировать обработчик? А если товаров будет 100?

2020-02-04 03:25 UTC, YaroslavWD commented
Спасибо за обратную связь. Обещал выслать в понедельник поэтому немного поторопился. 
Эталон не нужен. Про кнопки согласен что решение слишком не гибкое. 
> +let productData = API.products; 
Задумывался о том что-бы написать обработчик на изменение исходного api и обновление контента. 


> очень сложная и неподдерживаемая реализация, нужно все проще и нагляднее делать через innerHTML или insertAdjacentHTML
> 

Это про то что бы писать разметку прямо в js ? 



> какая-то излишне сложная конструкция, кажется тут все решается в одноу строчку через API.products.find.   
> 

Спасибо, учту на будущее это уже es6. Сейчас в работе поддерживаем ie11 поэтому не все могу использовать.


Иван, какой итог? 


> 3 февр. 2020 г., в 22:43, Ivan Bolshakov <notifications@github.com> написал(а):
> 
> @idbolshakov requested changes on this pull request.
> 
> привет, спасибо за выполнение ТЗ. К решению есть несколько вопросов:
> 
> есть возможность открыть одновременно несколько разных попапов заказа и корзины, что не совсем корректно
> In src/index.html <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374240734>:
> 
> >    <body>
> -    <main class="product-listing-wrapper">
> -    </main>
> +    <div class="container">
> +      <main class="main">
> +          <section class="catalog">
> +            <h1 class="catalog__title visually-hidden">Каталог товаров</h1>
> +            <div class="catalog__inner">
> +
> +              <!-- Эталон
> это тут зачем?
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374241617>:
> 
> > @@ -0,0 +1,122 @@
> +'use strict'
> +
> +let catalogContainer = document.querySelector(".catalog__inner");
> зачем все это в глобальной области видимости?
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374241652>:
> 
> > @@ -0,0 +1,122 @@
> +'use strict'
> +
> +let catalogContainer = document.querySelector(".catalog__inner");
> почему let ?
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374241706>:
> 
> > @@ -0,0 +1,122 @@
> +'use strict'
> +
> +let catalogContainer = document.querySelector(".catalog__inner");
> +let catalogProductTemplate = document.querySelector("#product-template");
> +let orderTemplate = document.querySelector("#order-template");
> +let basketTemplate = document.querySelector("#basket-template");
> +
> +let productData = API.products;
> зачем это в переменную?
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374242335>:
> 
> > +'use strict'
> +
> +let catalogContainer = document.querySelector(".catalog__inner");
> +let catalogProductTemplate = document.querySelector("#product-template");
> +let orderTemplate = document.querySelector("#order-template");
> +let basketTemplate = document.querySelector("#basket-template");
> +
> +let productData = API.products;
> +
> +const formatCostValue = (x) => {
> +    var parts = x.toString().split(".");
> +    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, " ");
> +    return parts.join(".");
> +};
> +
> +const createItem = (elementTemeplate, dataObject) => {
> очень сложная и неподдерживаемая реализация, нужно все проще и нагляднее делать через innerHTML или insertAdjacentHTML
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374242464>:
> 
> > +
> +const getElementById = (dataSet, idElement) => {
> +
> +    for (var i = 0; i < dataSet.length; i++) {
> +
> +        let elementForOrder = dataSet[i];
> +
> +        if(idElement == dataSet[i].id) {
> +            return elementForOrder;
> +        }
> +    }
> +}
> +
> +
> +
> +generateItem();
> код лучше выполнять после window.onload или подобного
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374243208>:
> 
> > +        elementCost.innerHTML = formatCostValue(Number(dataElement.price));
> +        elementImage.src = dataElement.img;
> +        catalogContainer.appendChild(basketPopup);
> +
> +        basketPopup.addEventListener('click', function(evt){
> +            evt.preventDefault();
> +            let target = evt.target;
> +
> +            if(target == elementBtnClose) {
> +                basketPopup.remove();
> +            }
> +        });
> +    }
> +}
> +
> +const getElementById = (dataSet, idElement) => {
> какая-то излишне сложная конструкция, кажется тут все решается в одноу строчку через API.products.find
> 
> In src/js/script.js <https://github.com/idbolshakov/apress-frontend_test_task/pull/40#discussion_r374243672>:
> 
> > +    let productTemplate = elementTemeplate.content.querySelector(".catalog__item");
> +    let product = productTemplate.cloneNode(true);
> +    let elementTitle = product.querySelector(".catalog__item-title");
> +    let elementCost = product.querySelector(".catalog__item-cost-value");
> +    let elementImage = product.querySelector(".catalog__item-img");
> +    let orderBtn = product.querySelector(".catalog__item-btn--order");
> +    let basketBtn = product.querySelector(".catalog__item-btn--basket");
> +
> +    elementTitle.innerHTML = dataObject.title;
> +    elementCost.innerHTML = formatCostValue(Number(dataObject.price));
> +    elementImage.src = dataObject.img;
> +    product.id = dataObject.id;
> +    orderBtn.setAttribute('data-id', dataObject.id);
> +    basketBtn.setAttribute('data-id', dataObject.id);
> +
> +    orderBtn.addEventListener("click", createOrder);
> зачем для каждой кнопки регистрировать обработчик? А если товаров будет 100?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/idbolshakov/apress-frontend_test_task/pull/40?email_source=notifications&email_token=AI3PDPYVZ2M33HUYCM2V2KTRBBJUXA5CNFSM4KPFQK42YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCUA3WKQ#pullrequestreview-352434986>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AI3PDP7FYWP2FYOS5EFJCKLRBBJUXANCNFSM4KPFQK4Q>.
>

2020-02-06 10:02 UTC, closed without merging