Тестовое Иванов Сергей
idbolshakov/apress-frontend_test_task pull request #55
Opened 2021-01-20 13:36 UTC by genjin145

2021-01-24 18:29 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ. По решению есть несколько вопросов:

1. решение не открывается в браузере без поднятия дополнительного сервера и нет инструкции как поднять решение
![image](https://user-images.githubusercontent.com/17525238/105639795-019e6900-5e9c-11eb-907a-573011b128d3.png)

2021-01-24 18:42 UTC, idbolshakov requested changes

2021-01-24 18:42 UTC, idbolshakov commented on src/css/style.css
> +img {
почему решил задать стили прямо на элемент ?

2021-01-24 18:42 UTC, idbolshakov commented on src/css/style.css
> +  color: #CC2157;
Цвета в ксс повторяются несколько раз, как думаешь, с этим могут быть какие-то проблемы?

2021-01-24 18:42 UTC, idbolshakov commented on src/css/style.css
> +body {
какие-то системы/подходы организации css когда знаешь/применяешь?

2021-01-24 18:42 UTC, idbolshakov commented on src/index.html
> +          <a class="popup-cart__link-cart btn btn_primary" href="#">Перейти в корзину</a>
почему тут решил использовать элемент `<a>` ?

2021-01-24 18:42 UTC, idbolshakov commented on src/index.html
> +      <section class="popup popup-cart" id="popup-cart">
почему решил добавить `html`-код попапа корзины сюда?

почему решил сразу разместить в нем какой-то товар?

2021-01-24 18:42 UTC, idbolshakov commented on src/index.html
> +    <section class="popup popup-order" id="popup-order">
тот же вопрос к попапу заказа

2021-01-24 18:42 UTC, idbolshakov commented on src/js/classes/Popup.js
> +export class Popup {
почему решил сделать такой класс?

2021-01-24 18:42 UTC, idbolshakov commented on src/js/classes/Popup.js
> +export class Popup {
кажется, что тут все очень очень переусложнено. Ради того, чтобы обрабатывать открытие/закрытие попапа у тебя написан целый класс в 34 строчки, кажется ,что все это можно было разместить в 2-3 строчках  кода

2021-01-24 18:42 UTC, idbolshakov commented on src/js/classes/Popup.js
> +export class Popup {
есть идеи как сделать проще?

2021-01-24 18:42 UTC, idbolshakov commented on src/js/script.js
> +  root.insertAdjacentHTML('beforeend', html);
здесь у тебя происходит вставка шаблона через  `insertAdjacentHTML`, почему ниже ты напрямую манипулируешь атрибутами и контентом через dom api ? почему решил совместить два подхода?

2021-01-24 18:42 UTC, idbolshakov commented on src/js/script.js
> +      setTimeout(() => popupCart.open(), 20);
зачем здесь таймауты?

2021-01-25 15:12 UTC, genjin145 commented on src/css/style.css
> +img {
Картинка часто используемый элемент, а стандартное поведение не удовлетворяет результату. (если картинка большая она выходит за границу родителя)

2021-01-25 15:12 UTC, genjin145 commented on src/css/style.css
> +  color: #CC2157;
Конечно, к примеру если дизайнер решит поменять цветовую палитру.
Можно в :root задать css переменные.

2021-01-25 15:12 UTC, genjin145 commented on src/css/style.css
> +body {
Обычно для верстки использую БЭМ + scss
scss/
├── blocks/
└── style.scss
Знаком с css модулями

2021-01-25 15:13 UTC, genjin145 commented on src/index.html
> +          <a class="popup-cart__link-cart btn btn_primary" href="#">Перейти в корзину</a>
Слово "перейти" меня убедило что это ссылка)

2021-01-25 15:16 UTC, genjin145 commented on src/index.html
> +      <section class="popup popup-cart" id="popup-cart">
Чтобы положение popup зависело от header
Забыл удалить текст и src

2021-01-25 15:22 UTC, genjin145 commented on src/index.html
> +    <section class="popup popup-order" id="popup-order">
Здесь попап отдельным окном, поэтому отдельно.
Не хотел рендорить через js чтобы не терять состояние формы

2021-01-25 15:29 UTC, genjin145 commented on src/js/classes/Popup.js
> +export class Popup {
Зачастую попап может быть сложным с различными настройками, задел на будущее
Можно было бы повесить на document click и через делегирование описать открытие \ закрытие или можно написать отдельные функции

2021-01-25 15:32 UTC, genjin145 commented on src/js/script.js
> +  root.insertAdjacentHTML('beforeend', html);
Хотел использовать addEventListener (позволяет обрабатывать несколько обработчиков возможно метрики появятся или что то еще)

2021-01-25 15:38 UTC, genjin145 commented on src/js/script.js
> +      setTimeout(() => popupCart.open(), 20);
Сначала происходит закрытие всех окон, затем через некоторое время открытие корзины.
Решил использовать простое решение, как вариант можно создать кастомное событие у класса Popup при закрытии

2021-01-26 16:12 UTC, closed without merging