Тестовое задание Настя
idbolshakov/apress-frontend_test_task pull request #56
Opened 2021-01-20 16:05 UTC by rascal666

Тестовое задание, буду рада обратной связи

2021-01-24 19:43 UTC, idbolshakov requested changes
Привет! Спасибо за выполнение ТЗ. Визуально все выглядит круто. По коду есть несколько вопросов:

2021-01-24 19:43 UTC, idbolshakov commented on src/api/products.js
> +let pro = API.products
1. зачем эта переменная?
2. почему let?
3. зачем столько пробелов?

2021-01-24 19:43 UTC, idbolshakov commented on src/api/root.js
> +const ROOT_PRODUCTS = document.getElementById('products');
а этот файл зачем ?

2021-01-24 19:43 UTC, idbolshakov commented on src/index.html
> +		<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" r
почему выбран такой способ подключения шрифтов?

какие могут быть с этим проблемы?

2021-01-24 19:43 UTC, idbolshakov commented on src/index.html
> +		<link rel="stylesheet" href="https://www.pulscen.ru/system/ckeditor_assets/attachments/226405/popap.css" />
аналогичный вопрос

2021-01-24 19:43 UTC, idbolshakov commented on src/assets/css/index.css
> +/** @format */
а почему у тебя есть  `src/assets/css/index.css` и `src/assets/index.css` ?

2021-01-24 19:43 UTC, idbolshakov commented on src/assets/js/modal.js
> +    onArray.forEach(event => {
почему переменная называется `event` ?

2021-01-24 19:43 UTC, idbolshakov commented on src/assets/js/modal.js
> +    let modal = e.target.getAttribute('data-id');
почему объявлена переменная через `let` ? не совсем удачное название для переменной

2021-01-24 19:43 UTC, idbolshakov commented on src/component/product.js
> +class Products {
почему решила оформить этот как класс?

2021-01-24 19:43 UTC, idbolshakov commented on src/index.html
> +		<button type="text"></button>
а этот как используется?

2021-01-25 08:08 UTC, rascal666 commented on src/api/products.js
> +let pro = API.products
1. да, если все таки обьявлять эту переменную, то должно быть const
2. можно убрать и обращатся сразу через API.products

2021-01-25 08:12 UTC, rascal666 commented on src/index.html
> +		<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" r
Такой способ подключения шрифтов обычно используется для быстрых решений. 
Правильнее было бы подключить через font-family
проблемы - старница не загрузится

2021-01-25 08:15 UTC, rascal666 commented on src/index.html
> +		<link rel="stylesheet" href="https://www.pulscen.ru/system/ckeditor_assets/attachments/226405/popap.css" />
тут у меня уже был разработан popap для коммерческих посадок пульса цен.
правильнее было бы прописать все в данном тестовом задании.

2021-01-25 08:30 UTC, rascal666 commented on src/assets/css/index.css
> +/** @format */
это вроде старое изменение, я пути меняла

2021-01-25 08:32 UTC, rascal666 commented on src/assets/js/modal.js
> +    onArray.forEach(event => {
можно назвать согласно выполняемым действиям.

2021-01-25 08:33 UTC, rascal666 commented on src/assets/js/modal.js
> +    let modal = e.target.getAttribute('data-id');
да, лучше const т.к не изменяемая переменная.

2021-01-25 08:41 UTC, rascal666 commented on src/index.html
> +		<button type="text"></button>
<div class="products" id="products"></div>  -  туда выводятся данные из API.products
<button type="text"></button> - забыла убрать

2021-01-25 08:48 UTC, rascal666 commented on src/api/root.js
> +const ROOT_PRODUCTS = document.getElementById('products');
можно эту строку перенести в product.js

2021-01-31 21:03 UTC, closed without merging