Тестовое задание, Думлер Олег
idbolshakov/apress-frontend_test_task pull request #57
Opened 2021-01-21 05:17 UTC by FonDumik

2021-01-24 20:23 UTC, idbolshakov requested changes
привет. Спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. При клике на кнопку "заказать" выпадает ошибка в консоль и попап не закрывается
2. при попытке нажать на кнопку "заказать" нескольких товаров, совсем едет верстка
![image](https://user-images.githubusercontent.com/17525238/105642172-ee929580-5ea9-11eb-9c63-c1050416f0f0.png)

2021-01-24 20:23 UTC, idbolshakov commented on src/css/styles.css
> +  background: url("https://lh3.googleusercontent.com/D8AIlc1NjWzlp97T4nr0_mBpjtOtHQcnEZRcMbp_nzsVJk26Eku42dj8YZOakA8V2w=s180");
почему решил добавить иконку таким способом? какие могут быть с этим проблемы?

какие еще есть варианты?

2021-01-24 20:23 UTC, idbolshakov commented on src/css/styles.css
> +body,
почему решил организовать ксс таким образом?

2021-01-24 20:23 UTC, idbolshakov commented on src/index.html
> +      <a class="basket_link" href="#"> Перейти в корзину </a>
почему этот элемент решил сделать с помощью тега `<a>` ?

2021-01-24 20:23 UTC, idbolshakov commented on src/js/app.js
> +          <button class="button btn-red orderNow" data-product-value="${i}">Заказать</button>
почему у кнопки нет атрибута `type` ?

2021-01-24 20:23 UTC, idbolshakov commented on src/js/app.js
> +for (let i = 0; i < API.products.length; i++) {
как-то можно оптимизировать эту конструкцию?

2021-01-24 20:23 UTC, idbolshakov commented on src/js/app.js
> +let toBasketBtns = document.querySelectorAll(".toBasket"),
почему `let` ?

2021-01-24 20:23 UTC, idbolshakov commented on src/js/app.js
> +toBasketBtns.forEach((btn) => {
знаком с делегированием событий?

2021-01-25 05:07 UTC, FonDumik commented on src/css/styles.css
> +  background: url("https://lh3.googleusercontent.com/D8AIlc1NjWzlp97T4nr0_mBpjtOtHQcnEZRcMbp_nzsVJk26Eku42dj8YZOakA8V2w=s180");
Конкретной причины выбора именно этого способа не было. Возможные проблемы: изображение не будет загружено с сервера на стороне клиента при наличии блокировок, увеличится время загрузки контента. Другие варианты: скачать изображение и добавить его локально

2021-01-25 05:12 UTC, FonDumik commented on src/css/styles.css
> +body,
Конкретных причин не было. Решил выбрать тот способ, который был привычнее на учебных проектах

2021-01-25 05:14 UTC, FonDumik commented on src/index.html
> +      <a class="basket_link" href="#"> Перейти в корзину </a>
Потому что из названия следует, что это ссылка, которая ведёт на страницу корзины

2021-01-25 05:18 UTC, FonDumik commented on src/js/app.js
> +          <button class="button btn-red orderNow" data-product-value="${i}">Заказать</button>
type используется при создании формы и  создании логики для работы кнопок в этой форме. Так как  это всего лишь список товаров, было принято решение не использовать `form` в этой верстке

2021-01-25 05:20 UTC, FonDumik commented on src/js/app.js
> +let toBasketBtns = document.querySelectorAll(".toBasket"),
В силу малого опыта на учебных проектах привык использовать `let` , так как это не имело серьезного значения

2021-01-25 05:34 UTC, FonDumik commented on src/js/app.js
> +for (let i = 0; i < API.products.length; i++) {
Переписал с помощью цикла `forEach`

2021-01-25 05:51 UTC, FonDumik commented on src/js/app.js
> +toBasketBtns.forEach((btn) => {
Знаком с концепцией. В контексте этой задачи решил сделать код простым. Сейчас внёс небольшие изменения в обработчик клика `toBasketBtns `и `makeOrderBtns `, но не уверен, правильное ли такое решение.

2021-01-25 06:04 UTC, FonDumik commented
Доброе утро! Ознакомился с review. Благодарю за вопросы. Оставил комментарии, также сделал pull request в свой репозиторий с изменениями после rewiew. https://github.com/FonDumik/apress-frontend_test_task/pull/2 
Git почему то не даёт сделать новый коммит в эту ветку

2021-01-31 21:03 UTC, closed without merging