Николай Жданов тестовое задание
idbolshakov/apress-frontend_test_task pull request #58
Opened 2021-01-21 18:46 UTC by HerzogKlaus

Ссылка на резюме: https://ekaterinburg.hh.ru/resume/188e418fff0621b6d20039ed1f44386c66486a

2021-01-24 20:38 UTC, idbolshakov requested changes
Привет! спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. При удалении последнего товара из корзины в консоле появляется ошибка

![image](https://user-images.githubusercontent.com/17525238/105642660-d83a0900-5eac-11eb-805d-a6b6ed761deb.png)

2. в ТЗ указано: `можно использовать ES6+, но без babel, webpack, шаблонизаторов, постпроцессоров и пр.;` у тебя в решении зачем то `.editorconfig` и `.prettierrc` зачем они?

2021-01-24 20:38 UTC, idbolshakov commented on .editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
зачем в решении этот файл?

2021-01-24 20:38 UTC, idbolshakov commented on .prettierrc
> +{
и этот?

2021-01-24 20:38 UTC, idbolshakov commented on src/css/style.css
> +  font-family: Arial;
почему выбрал этот шрифт?

2021-01-24 20:38 UTC, idbolshakov commented on src/css/style.css
> +  background-color: #eeeeef;
несколько повторяющихся цветов, как можно оптимизировать?

2021-01-24 20:38 UTC, idbolshakov commented on src/css/style.css
> +* {
почему решил сложить все стили в один файл?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/modules/Product.js
> +class Product {
почему решил оформить в виде класса?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/modules/Product.js
> +  constructor(title, price, image, id = null) {
как используются все эти свойства объявленные в конструкторе?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/modules/Product.js
> +class Product {
получается, что твой класс объявлен в глобальной области видимости. С этим могут быть проблемы?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/script.js
> +for (let product of API.products) {
как можно оптимизировать эту конструкцию?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/script.js
> +          <span class="busket__delete-btn" onclick="this.parentNode.remove();productsArray.splice(productsArray.findIndex(item => Number(item.id) === ${i}), 1)">&#10008;</span>
почему тут решил использовать инлайн обработчик события ?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/script.js
> +    let currentOrderProduct = new Product(API.products[i].title, API.products[i].price, API.products[i].img);
зачем нужен этот объект?

2021-01-24 20:38 UTC, idbolshakov commented on src/js/script.js
> +  document.querySelectorAll(".product__item-button--busket")[i].addEventListener("click", () => {
знаком с подходом делегирования событий?

2021-01-25 09:54 UTC, HerzogKlaus commented on .editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
Файл исключительно для форматирования кода, установки одинаковых отступов для всех файлов,

2021-01-25 09:54 UTC, HerzogKlaus commented on .prettierrc
> +{
Аналогично первому

2021-01-25 09:54 UTC, HerzogKlaus commented on src/css/style.css
> +  font-family: Arial;
Первый пришедший в голову дефолтный шрифт более менее похожий на шрифт из макета

2021-01-25 09:55 UTC, HerzogKlaus commented on src/css/style.css
> +  background-color: #eeeeef;
Возможно создать один общий класс для элементов с повторяющимся цветом, либо занести в переменную при помощи препроцессоров

2021-01-25 09:56 UTC, HerzogKlaus commented on src/css/style.css
> +* {
Стилей не так много и в рамках тестового задания думал это разрешено

2021-01-25 09:57 UTC, HerzogKlaus commented on src/js/script.js
> +for (let product of API.products) {
Возможно при помощи деструктуризации или вынесения API.products в отдельную переменную

2021-01-25 10:00 UTC, HerzogKlaus commented on src/js/script.js
> +          <span class="busket__delete-btn" onclick="this.parentNode.remove();productsArray.splice(productsArray.findIndex(item => Number(item.id) === ${i}), 1)">&#10008;</span>
Возникала ошибка связанная с событием для несуществующего элемента. Не самое лучшее решение конечно, можно было сделать по другому. Просто не хотелось создавать событие onload или подобное

2021-01-25 10:04 UTC, HerzogKlaus commented on src/js/script.js
> +    let currentOrderProduct = new Product(API.products[i].title, API.products[i].price, API.products[i].img);
Для отображения выбранного товара в попапе

2021-01-25 10:05 UTC, HerzogKlaus commented on src/js/modules/Product.js
> +class Product {
Проблемы могут быть. Классы можно было вообще не использовать в этом задании, моя ошибка

2021-01-25 10:10 UTC, HerzogKlaus commented on src/js/script.js
> +  document.querySelectorAll(".product__item-button--busket")[i].addEventListener("click", () => {
Можно было повесить событие клика на селектор родительского элемента кнопок я думаю

2021-01-31 08:38 UTC, closed without merging