Тестовое задание Амбражевич Вячеслав
idbolshakov/apress-frontend_test_task pull request #59
Opened 2021-01-22 09:38 UTC by iamitd

случайно запушил с другого гита

2021-01-24 20:54 UTC, idbolshakov requested changes
привет! спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. при добавлении нескольких товаров в корзину видно только первый
2.  если попробовать добавить несколько товаров в корзину, то корзина не закрывается

2021-01-24 20:54 UTC, idbolshakov commented on src/listing.js
> +class Listing {
почему решил оформить это в класс?

2021-01-24 20:54 UTC, idbolshakov commented on src/listing.js
> +            <button class="products-element-cart-button" id="${id}">В корзину</button>
почему у кнопки нет атрибута `type` ?

2021-01-24 20:54 UTC, idbolshakov commented on src/listing.js
> +            <img src="${img}" class="products-element-img"/>
почему у картинки нет атрибута `alt` ?

2021-01-24 20:54 UTC, idbolshakov commented on src/popup-cart.js
> +    let popupCartCloseButton = document.querySelector('.popup-cart-close');
почему `let` ?

2021-01-24 20:54 UTC, idbolshakov commented on src/buttons.js
> +toCartButton.forEach((btn) => {
знаком с делегированием событий?

2021-01-24 20:54 UTC, idbolshakov commented on src/styles.css
> +.products-container {
почему решил сложить весь css  в один файл?

2021-01-26 10:41 UTC, iamitd commented on src/listing.js
> +            <button class="products-element-cart-button" id="${id}">В корзину</button>
добавил

2021-01-26 10:41 UTC, iamitd commented on src/listing.js
> +            <button class="products-element-cart-button" id="${id}">В корзину</button>
должны были быть

2021-01-26 10:41 UTC, iamitd commented on src/popup-cart.js
> +    let popupCartCloseButton = document.querySelector('.popup-cart-close');
Нужно const, поправил

2021-01-26 10:41 UTC, iamitd commented on src/buttons.js
> +toCartButton.forEach((btn) => {
Ознакомился, реализовал

2021-01-26 10:42 UTC, iamitd commented on src/listing.js
> +            <img src="${img}" class="products-element-img"/>
добавил, должен был быть

2021-01-26 10:43 UTC, iamitd commented on src/styles.css
> +.products-container {
Стоило раскидать по разным, когда делал не задумался

2021-01-26 12:23 UTC, closed without merging