test
idbolshakov/apress-frontend_test_task pull request #6
Opened 2019-08-26 08:49 UTC by Romchik908

Малышкин Роман

2019-08-26 19:03 UTC, idbolshakov requested changes
Привет! Спасибо за выполнение тестового задания! Все работает так как нужно, но к реализации есть несколько вопросов

2019-08-26 19:03 UTC, idbolshakov commented on src/js/main.js
> +console.log(API.products);
Зачем оно тут?

2019-08-26 19:03 UTC, idbolshakov commented on src/js/main.js
> +    console.log(id);
и тут?

2019-08-26 19:03 UTC, idbolshakov commented on src/css/main.css
> +.item img{
почему решил все стили разместить в одном файле?

2019-08-26 19:03 UTC, idbolshakov commented on src/css/main.css
> +    font-family: Century Gothic;
Использовать нестандартное семейство шрифтов без их подключения в коде - плохая практика

2019-08-26 19:03 UTC, idbolshakov commented on src/css/main.css
> +#popup{
Почему решил для попапов задавать стили не через селекор класса, а через селектор айдишника?

2019-08-26 19:03 UTC, idbolshakov commented on src/css/main.css
> +    background-color: deeppink;
цвет совсем не похож на тот что в макете, почему выбрал именно эти цвета?

2019-08-26 19:03 UTC, idbolshakov commented on src/js/main.js
> +    document.getElementById("main").insertAdjacentHTML('beforeend', '<div class="item"> <img src="'+ API.products[i].img+ '"> <div class="info"> <p class="description">'+ API.products[i].title+'</p>
километровые строчки в коде - плохая практика

2019-08-26 19:03 UTC, idbolshakov commented on src/js/main.js
> +    document.getElementById("popup").style.display = "block";
почему решил управлять стилями напрямую из js ? Лучше в таких случаях задавать в коде css-классы, а сами эти классы уже описывать в css-файлах

2019-08-26 19:03 UTC, idbolshakov commented on src/js/main.js
> +console.log(API.products);
и тот же вопрос к коду, почему решил весь код разместить в одном файле?

писать код в глобальном скоупе - плохая практика

2019-08-27 06:46 UTC, Romchik908 commented on src/js/main.js
> +console.log(API.products);
console.log просто забыл убрать. Это была проверка, получаются ли данные из файла products
код разместил в одном файле потому, что он относится к одной странице, да и его не так много

2019-08-27 06:48 UTC, Romchik908 commented on src/js/main.js
> +    console.log(id);
и тут тоже забыл, проверял верно ли приходит передаваемый параметр

2019-08-27 06:49 UTC, Romchik908 commented on src/css/main.css
> +.item img{
все относятся к одной странице, да и не так много их

2019-08-27 07:42 UTC, Romchik908 commented on src/css/main.css
> +    background-color: deeppink;
в моем браузере был похож, да и соблюдение цветов не было условием

2019-08-27 07:51 UTC, Romchik908 commented on src/css/main.css
> +#popup{
в коде было проще управлять элементами html через айди, чем через класс

2019-08-27 07:52 UTC, Romchik908 commented on src/js/main.js
> +    document.getElementById("popup").style.display = "block";
да, не подумал, было бы проще менять класс, чем стили

2019-08-27 08:04 UTC, Romchik908 commented on src/css/main.css
> +    font-family: Century Gothic;
вроде нормально показывалось во всех браузерах, поэтому так и оставил

2019-08-27 08:13 UTC, Romchik908 commented on src/js/main.js
> +    document.getElementById("main").insertAdjacentHTML('beforeend', '<div class="item"> <img src="'+ API.products[i].img+ '"> <div class="info"> <p class="description">'+ API.products[i].title+'</p>
так было проще и быстрее сделать
можно было построить эти popup по другому, но это бы занято кучу строчек в коде

2019-08-27 13:16 UTC, idbolshakov commented on src/css/main.css
> +    font-family: Century Gothic;
показывалось нормально, потому что у тебя эти шрифты установлены в системе, а у других людей их нет

2019-08-27 13:21 UTC, merged