(Feature): Finish test task: Андрей Никитюк
idbolshakov/apress-frontend_test_task pull request #60
Opened 2021-01-24 20:47 UTC by Ingwaaz

Почта: ingwaazdesign@mail.ru

2021-01-31 22:17 UTC, idbolshakov requested changes
привет. Спасибо за выполнение ТЗ. В условии ТЗ было условие не использовать библиотеки, постпроцессоры и пр. Сторонние серверы в том числе. 

Почему не удалось сделать решение, которые просто открывается в браузере без необходимости использовать сервер?

---

`.idea` директорию почему решил добавить по гит ?

---

у тебя в коде есть и ассеты и компоненты, а также компоненты отдельно разделятся на css и js компоненты, почему применил такой подход?

2021-01-31 22:17 UTC, idbolshakov commented on src/components/css/cart/index.css
> +#product-cart.close {
у тебя используются и селекторы через классы и селекторы через id. Почему решил делать так?

2021-01-31 22:17 UTC, idbolshakov commented on src/index.html
> +      <img
почему решил положить иконку корзину в html тэг, а не, например, добавить ее через css ?

2021-01-31 22:17 UTC, idbolshakov commented on src/components/js/module/layouts/layouts.js
> +const getTemplateList = (data = []) => {
почему решил сложить все шаблоны в один файл?

2021-02-01 05:44 UTC, Ingwaaz commented on src/components/css/cart/index.css
> +#product-cart.close {
Решил не дублировать запись по типу
`<div id="hello" class="hello"></div>`

2021-02-01 05:44 UTC, Ingwaaz commented
> привет. Спасибо за выполнение ТЗ. В ТЗ было условие не использовать библиотеки, постпроцессоры и пр. Сторонние серверы в том числе.
> 
> Почему не удалось сделать решение, которые просто открывается в браузере без необходимости использовать сервер?
> 
> `.idea` директорию почему решил добавить по гит ?
> 
> у тебя в коде есть и ассеты и компоненты, а также компоненты отдельно разделятся на css и js компоненты, почему применил такой подход?

2021-02-01 05:52 UTC, Ingwaaz commented on src/index.html
> +      <img
Честно говоря не знал что из этого оптимизирование, поэтому решил сделать так. Так же можно предзагружать изображения для улучшения производительности. Но иконка не несет на себе смысловой нагрузки, поэтому можно было засунуть в css. Это не повлияет на seo и производительность

2021-02-01 05:54 UTC, Ingwaaz commented on src/components/js/module/layouts/layouts.js
> +const getTemplateList = (data = []) => {
Тз небольшое, поэтому решил не разделять полностью все на компоненты. На реальном проекте разделил бы и доработал функции что бы они действительно возвращали переиспользуемый шаблон.

2021-02-01 05:58 UTC, Ingwaaz commented
> привет. Спасибо за выполнение ТЗ. В ТЗ было условие не использовать библиотеки, постпроцессоры и пр. Сторонние серверы в том числе.
 > Почему не удалось сделать решение, которые просто открывается в браузере без необходимости использовать сервер?
 
 По привычке запустил через локальный сервер
 
 > `.idea` директорию почему решил добавить по гит ?
 
 Не заметил как эту папку создал webstor, а так конечно в гит игнор ее
 
> у тебя в коде есть и ассеты и компоненты, а также компоненты отдельно разделятся на css и js компоненты, почему применил такой подход?

Я не особо сильно знаком с паттернами программирования, чаще всего пишу на nuxt или next. MVC использовать в этом тз не стал. Решил более ли менее повторить архитектуру nuxt. Сейчас думаю что лучше было бы сделать по такому типу
/src/components/common/Card/index.js
/src/components/common/Card/Card.module.css

2021-02-01 08:57 UTC, idbolshakov commented on src/components/css/cart/index.css
> +#product-cart.close {
а зачем вообще id используется?

2021-02-01 12:12 UTC, Ingwaaz commented on src/components/css/cart/index.css
> +#product-cart.close {
через id удобно манипулировать узлом, но это не обязательно. Так же в css селектор # имеет больший приоритет чем .class

2021-03-06 19:02 UTC, closed without merging