Тестовое задание, Огаркова Анастасия
idbolshakov/apress-frontend_test_task pull request #62
Opened 2021-01-25 09:54 UTC by Nasenka

2021-01-31 23:17 UTC, idbolshakov requested changes
привет. спасибо за выполнение тз. Визуально все выглядит норм. К коду есть несколько вопросов:

1. Почему решила добавить `font-awesome` ?

2021-01-31 23:17 UTC, idbolshakov commented on src/css/style.css
> +	display: block !important;
почему тут нужен `important` ?

2021-01-31 23:17 UTC, idbolshakov commented on src/css/style.css
> +#overlay {
почему селектор к id ? Почему нельз было в и в этом случае использовать селектора к классу?

2021-01-31 23:17 UTC, idbolshakov commented on src/img/shopping-cart.svg
> +<?xml version="1.0"?>
почему svg не пожаты?

2021-01-31 23:17 UTC, idbolshakov commented on src/index.html
> +	<template id="product-template">
почему этот шаблон решила положить в html ? Можно ли было через js тоже самое сделать7

2021-01-31 23:17 UTC, idbolshakov commented on src/index.html
> +			<button class="btn btn-order btn-popup-order">Отправить</button>
почему у `button` нет атрибута `type` ?

2021-01-31 23:17 UTC, idbolshakov commented on src/js/main.js
> +window.addEventListener('scroll', function () {
а вместо этого кода нельз было использовать `position:fixed` или `position: sticky` в css?

2021-01-31 23:17 UTC, idbolshakov commented on src/js/main.js
> +API.products.forEach(function createProductItem(item) {
у тебя получилось очень императивное решение. Представь, что со временем верстка изменится, нужно будет добавить больше тегов и тд. Тебе придется руками  клонировать ноды, менять атрибуты и пр.

проще использовать `innerHTML` `insertAdjacentHTML`  чтобы DOM API все сделал за тебя. Так будет проще и намного более читаемо

2021-02-01 07:03 UTC, Nasenka commented on src/css/style.css
> +	display: block !important;
Important использовала, потому что класс show добавляется и к формам и к блоку, который затеняет фон при открытии форм. 
И сразу тут же отвечу на следующий вопрос про `#overlay`. Использовала его, т.к недавно решала домашнее задание в курсах от Skillbox и там для примера был предложен такой вариант использования этого блока. Поэтому решила сделать так же.
Как решение данных 2 замечаний, да, можно было бы использовать классы и еще добавлять/удалять затеняющий тег по открытию/закрытию форм. 
Если необходимо, могу поправить.

2021-02-01 07:04 UTC, Nasenka commented on src/img/shopping-cart.svg
> +<?xml version="1.0"?>
Если бы в проекте было много файлов, картинок и иконок, то да, конечно было бы необходимо пожать svg, но т.к она у меня одна единственная, то решила оставить так.
Если необходимо, могу поправить.

2021-02-01 07:05 UTC, Nasenka commented on src/index.html
> +	<template id="product-template">
Не так давно узнала о существовании тега <template>, решила попробовать его. Думаю, в js тоже можно, но мне кажется, что через html получается более читаемо.

2021-02-01 07:05 UTC, Nasenka commented on src/index.html
> +			<button class="btn btn-order btn-popup-order">Отправить</button>
Когда создавала верстку, случайно удалила и забыла восстановить.
Если необходимо, могу поправить.

2021-02-01 07:05 UTC, Nasenka commented on src/js/main.js
> +window.addEventListener('scroll', function () {
Использовать можно, но т.к это тестовое задание, которое может показать навыки, решила сделать так, мелочь, но все же =) И опять же, никаких строгих указаний ТЗ на этот счет не было.

2021-02-01 07:06 UTC, Nasenka commented on src/js/main.js
> +API.products.forEach(function createProductItem(item) {
Возможно. Но в любом случае, если не пользоваться доп.инстурментами и шаблонизаторами, то мне кажется, что так и так вышло бы относительно императивно. Даже если использовать `innerHTML` и `insertAdjacentHTML`, то при изменении верстки в любом случае придется править это и в коде js, даже если работы будет меньше. А если кода будет очень много, то и с `innerHTML` и `insertAdjacentHTML` придется повозиться и найти нужные места для правок. 
Плюс, если прописывать теги через js и не пользоваться доп.инстурментами и шаблонизаторами, то больше шансов допустить синтаксическую ошибку в тегах, т.к там даже подсветки синтаксиса не будет

2021-02-01 07:08 UTC, Nasenka commented
> привет. спасибо за выполнение тз. Визуально все выглядит норм. К коду есть несколько вопросов:
> 
> 1. Почему решила добавить `font-awesome` ?

Изначально хотела использовать font-awesome для подключения иконки корзины и крестиков в попапах, но потом передумала, а файл стилей удалить забыла.

2021-03-06 19:01 UTC, closed without merging