feat(app): добавлен список товаров и модальные окна
idbolshakov/apress-frontend_test_task pull request #63
Opened 2021-01-29 04:57 UTC by lshishkin

2021-01-31 23:26 UTC, idbolshakov requested changes
привет. Спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. при добавлении товара в корзину, вылезает модальное окно, которое блокирует взаимодействие с остальной страницей. Кажется, что такого быть не должно

2. почему решил сложить весь js в один файл и весь css в один файл?

2021-01-31 23:26 UTC, idbolshakov commented on src/style.css
> +    background-size: contain !important;
почему тут нужны импортанты?

2021-01-31 23:26 UTC, idbolshakov commented on src/style.css
> +  #close-order{
почему тут нужен селектор к `id` ?

2021-01-31 23:26 UTC, idbolshakov commented on src/api/products.js
> +//Чтобы проект запускался даже без запуска сервера я поместил компоненты в этот же файл ниже
а почему запуск без сервера невозможен, если компоненты разместить в другом файле?

2021-01-31 23:26 UTC, idbolshakov commented on src/api/products.js
> +  const container = elements[0] || null;
зачем тут `null` как один из возможнных значений для `container` ? 

если вдруг будет null, то весь код ниже упадет с ошибкой

2021-02-02 08:52 UTC, lshishkin commented on src/style.css
> +    background-size: contain !important;
Мне нужно было в блоках с картинками вместо "background" использовать "background-image". Тогда бы все работало без "!important". А сейчас инлайновый "background" затирает эти значения

2021-02-02 08:53 UTC, lshishkin commented on src/style.css
> +  #close-order{
Для стилизации крестика заказа

2021-02-02 09:04 UTC, lshishkin commented on src/api/products.js
> +//Чтобы проект запускался даже без запуска сервера я поместил компоненты в этот же файл ниже
Можно попробовать в теге script указать type="module", но браузер блокирует содержимое из-за политики cors. Конечно и cors можно отключить, но я решил что правильнее будет сделать ТЗ без импортов.

2021-02-02 09:07 UTC, lshishkin commented on src/api/products.js
> +  const container = elements[0] || null;
Забыл ниже сделать проверку)

`if(container){
container.innerHTML = App(state);
//И навешивание обработчиков сюда же
}
`

2021-02-02 09:11 UTC, lshishkin commented
> привет. Спасибо за выполнение ТЗ. К решению есть несколько вопросов:
> 
> 1. при добавлении товара в корзину, вылезает модальное окно, которое блокирует взаимодействие с остальной страницей. Кажется, что такого быть не должно
> 2. почему решил сложить весь js в один файл и весь css в один файл?

1) Наверное нужно было реализовать закрытие модального окна по клику вне его.
2) Чтобы была возможность открытия проекта без сервера

2021-03-06 19:01 UTC, closed without merging