Nt
idbolshakov/apress-frontend_test_task pull request #64
Opened 2021-01-31 17:45 UTC by OlegRC2

2021-01-31 23:33 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ.

При попытке открыть в браузере ничего не происходит и в консоли ошибки 
![image](https://user-images.githubusercontent.com/17525238/106401466-0e93fd00-6446-11eb-86dc-21ff5cdc2994.png)


зачем в решение добавляется файл `bootstrap-reboot.min.css` ?

2021-01-31 23:33 UTC, idbolshakov commented on src/css/blocks/popupBasket.css
> +.popup-basket {
рассинхрон с названием файла и фактическим названием блока

2021-01-31 23:33 UTC, idbolshakov commented on src/css/libs/fonts.css
> +@font-face {
кастомные шрифты действительно нужны для этого задания?

2021-01-31 23:33 UTC, idbolshakov commented on src/js/modules/basketPopup.js
> +    class ProductBasket extends Card {                                                                      // создаем класс окна корзины
почему решил использовать классы?

почему класс объявляется внутри функции?

2021-01-31 23:33 UTC, idbolshakov commented on src/js/modules/classes.js
> +export default class Card {                                                         // создаем общий класс с характеристиками товара
зачем этот класс?

2021-01-31 23:33 UTC, idbolshakov commented on src/js/modules/orderPopup.js
> +function orderPopup() {                                                                     // функция отображения окна заказа
зачем ты оборачиваешь класс в функцию а потом экспортируешь ее?

2021-02-01 19:01 UTC, OlegRC2 commented on src/css/blocks/popupBasket.css
> +.popup-basket {
При наименовании файлов и блоков не было цели создать строгое соответствие. Название файла отражает суть, в данном случае в файле содержатся множество стилей описывающих окно корзины. Та же логика применима и к остальным css файлам.

2021-02-01 19:04 UTC, OlegRC2 commented on src/css/libs/fonts.css
> +@font-face {
Нет не нужны, можно было использовать дефолтные.

2021-02-01 19:12 UTC, OlegRC2 commented on src/js/modules/basketPopup.js
> +    class ProductBasket extends Card {                                                                      // создаем класс окна корзины
В задании много элементов с одинаковой структурой. В этом случае, по моему мнению, оптимально построить все на классах. 

Класс внутри функции: 
- во-первых, для создания модульной структуры, чтобы весь функционал конкретного блока был написан в одном файле. 
- во-вторых, чтобы избежать множества импортов/экспортов и не запутаться в них (тут с расчетом на будущее, если проект будет дальше развиваться).

2021-02-01 19:19 UTC, OlegRC2 commented on src/js/modules/classes.js
> +export default class Card {                                                         // создаем общий класс с характеристиками товара
Принцип создания одного класса и наследования остальных классов от него в данном случае применен для исключения повторения кода, т.к. по сути задачи везде используются одни и те же данные из API.

2021-02-01 19:20 UTC, OlegRC2 commented on src/js/modules/orderPopup.js
> +function orderPopup() {                                                                     // функция отображения окна заказа
Выше ответил, чтобы избежать множества импортов/экспортов.

2021-02-01 19:30 UTC, OlegRC2 commented
> Привет. Спасибо за выполнение ТЗ.
> 
> При попытке открыть в браузере ничего не происходит и в консоли ошибки
> ![image](https://user-images.githubusercontent.com/17525238/106401466-0e93fd00-6446-11eb-86dc-21ff5cdc2994.png)
> 
> зачем в решение добавляется файл `bootstrap-reboot.min.css` ?

Приветствую, благодарю за код ревью. 

При решении задачи использовал плагин Live server в VS code. Запустить можно используя этот плагин или на любом локальном сервере.

Файл bootstrap-reboot.min.css нужен для установки базовых стилей, чтобы верстка во всех браузерах выглядела одинаково.

2021-02-14 07:17 UTC, closed without merging