(feat) Закончил тестовое задание | Александр Черных
idbolshakov/apress-frontend_test_task pull request #65
Opened 2021-03-04 12:51 UTC by chernykhal

2021-03-05 08:58 UTC, idbolshakov requested changes
Привет! спасибо за выполнение тз. К решению есть несколько вопросов:

1. при работе в консоль выводится отладочная информация, это действительно нужно? 
![image](https://user-images.githubusercontent.com/17525238/110091637-7d080a00-7dba-11eb-8b78-a1310bf4ef9c.png)

2021-03-05 08:58 UTC, idbolshakov commented on src/api/products.js
> +
зачем эти пустые строчки?

2021-03-05 08:58 UTC, idbolshakov commented on src/css/products.css
> +body {
по какому принципу разбивал ксс на файлы?

2021-03-05 08:58 UTC, idbolshakov commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
почему решил подключать шрифты с гугла?

2021-03-05 08:58 UTC, idbolshakov commented on src/js/cart.js
> +let cartProducts = [];
почему let?

2021-03-05 08:58 UTC, idbolshakov commented on src/js/cart.js
> +  const product = JSON.parse(
зачем тут JSON.parse в который передаем JSON.stringify?

2021-03-05 18:25 UTC, chernykhal commented
@idbolshakov, Здравствуйте!
1. Забыл убрать. Нет, не нужно.
2. Кажется веб шторм сам добавил, либо я случайно :)
3. Сначала была идея сделать все по БЭМ'у, и файловую структура тоже, но решил ограничиться этой структурой. Мне показалось, что тут всего два блока, это главный компонент с продуктами и попап компонент.
4. Самый удобный и простой способ.
5. Сделал let, так как в коде есть момент, когда я переопределяю эту переменную, поэтому const не подойдет. var - довольно старый вариант объявления переменных, в данном случае var бы так же работал, но я все же предпочитаю использовать let, вместо var.
6. Это эффективный способ глубокого клонирования простых объектов.

2021-03-06 19:01 UTC, idbolshakov commented
> Это эффективный способ глубокого клонирования простых объектов. С помощью метода stringify мы приводим объект в строку, затем считываем эту строку и превращаем в объект с помощью метода parse, при этом не создаем ссылки на родительский объект.

а для чего ты эту технику применил в данном решении?

2021-03-07 15:56 UTC, chernykhal commented
> > Это эффективный способ глубокого клонирования простых объектов. С помощью метода stringify мы приводим объект в строку, затем считываем эту строку и превращаем в объект с помощью метода parse, при этом не создаем ссылки на родительский объект.
> 
> а для чего ты эту технику применил в данном решении?

Чтобы можно было присвоить разные значения повторяющимся объектам. Для того, чтобы добавить в корзину один продукт несколько раз и при этом была возможность удалять один дубликаты этого продукта, нужно чтобы эти дубликаты продукта отличались чем то. Для этого я добавлял номер итерации(index) в каждый дубликат, но так как в джаваскрипте при копировании объекта в другую переменную не создается дубликат объекта, а только ссылка на этот объект. Каждый раз, когда добавлялся один и тот же продукт несколько раз, добавленные дубликаты не отличались ничем, так как получали один и тот же номер(index). В общем, чтобы была возможность удалять продукты из корзины.

2021-03-07 18:59 UTC, idbolshakov commented
> Чтобы можно было присвоить разные значения повторяющимся объектам. Для того, чтобы добавить в корзину один продукт несколько раз и при этом была возможность удалять один дубликаты этого продукта, нужно чтобы эти дубликаты продукта отличались чем то. Для этого я добавлял номер итерации(index) в каждый дубликат, но так как в джаваскрипте при копировании объекта в другую переменную не создается дубликат объекта, а только ссылка на этот объект. Каждый раз, когда добавлялся один и тот же продукт несколько раз, добавленные дубликаты не отличались ничем, так как получали один и тот же номер(index). В общем, чтобы была возможность удалять продукты из корзины.

кажется, что это не очень оптимальное решение. Какие видишь варианты оптимизации?

2021-03-08 10:14 UTC, chernykhal commented
> > Чтобы можно было присвоить разные значения повторяющимся объектам. Для того, чтобы добавить в корзину один продукт несколько раз и при этом была возможность удалять один дубликаты этого продукта, нужно чтобы эти дубликаты продукта отличались чем то. Для этого я добавлял номер итерации(index) в каждый дубликат, но так как в джаваскрипте при копировании объекта в другую переменную не создается дубликат объекта, а только ссылка на этот объект. Каждый раз, когда добавлялся один и тот же продукт несколько раз, добавленные дубликаты не отличались ничем, так как получали один и тот же номер(index). В общем, чтобы была возможность удалять продукты из корзины.
> 
> кажется, что это не очень оптимальное решение. Какие видишь варианты оптимизации?

Можно добавить для каждого продукта свойство quantity и просто увеличивать это свойство каждый раз, когда добавляется дубликат продукта

2021-05-14 08:56 UTC, closed without merging