page added. BaltikovaNP
idbolshakov/apress-frontend_test_task pull request #68
Opened 2021-04-28 15:40 UTC by Tasha-Ball

2021-04-29 13:00 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ. К реализации есть несколько вопросов.

1. Почему весь js код находится в папке `src/api` ?
2. зачем дублируется список продуктов который был объявлен в переменной API в файле  `src/api/products` ? 
3. По ксс вопрос, почему не использовала никакую систему организции ксса? По js вижу что были попытки разбить все на классы, стили же лежат все в куче
4. js код очень императивный и запутанный, не понятно что откуда и зачем, где-то элементы вставляются через innerHTML где то через createElement.  В будущем в таком коде очень сложно будет разобраться и внести какие-то изменения.

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +    padding-left: calc(50% - 570px);
зачем тут и ниже используется calc ?

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +    position: absolute;
зачем тут это свойство?

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +.product-listing-wrapper {
очень запутанный нейминг селекторов. Какие-то через-тире, какие-то через camelCase. Одни сокращенные img, другие без сокращений  - goodItem

нет системности, очень сложно поддерживать код такой будет

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +.img {
опять не понятно, класс называется так, как будто это картинка, а фактически это контейнер для картинки

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +    font-family: Lato;
Используется несистемный шрифт без подключения его на страницу. У 99.9% пользователей страница будет выглядеть не так как ты планировала

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +    z-index: 1000;
для чего такой большой z-index ?

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +    z-index: 99999;
а тут еще больше)

2021-04-29 13:00 UTC, idbolshakov commented on src/styles/style.css
> +.order__top {
о, уже элементы БЭМа пошли)

2021-04-29 13:00 UTC, idbolshakov commented on src/api/button.js
> +export class Button {
у тебя в коде 2 класса с названием Button. Зачем и почему?

2021-04-29 13:00 UTC, idbolshakov commented on src/api/gooditem.js
> +          const block = document.createElement('div')
для чего создавать элемент через createElement, а потом вставлять в него разметку через innerHTML ?

2021-04-29 13:00 UTC, idbolshakov commented on src/api/main.js
> +  if (event.target == document.querySelector('.pop-up-cart')) {
у тебя на каждый клик будет производиться операция поиска в DOM дереве через querySelector. Это не очень хорошая вещь. Есть мысли как это исправить?

2021-04-29 13:00 UTC, idbolshakov commented on src/api/main.js
> +window.onclick = function(event) {
Безымянный обработчик события - плохая практика, не понятно что он делает и зачем

2021-04-29 13:00 UTC, idbolshakov commented on src/api/page.js
> +class List {
такое ощущение, что желаение разбивать код на модули закончилось и решила спихнуть все в один файл помойку под конец. Это плохая практика, а также говорит о том, что тебе самой под конец уже показалось очень неудобным выбранный в начале подход)

2021-04-29 13:06 UTC, idbolshakov commented
Еще по коду увидел, что у тебя на странице два тега main один за другим - так делать нельзя

2021-04-30 09:47 UTC, Tasha-Ball commented on src/styles/style.css
> +    padding-left: calc(50% - 570px);
для выравнивания по центру

2021-04-30 09:47 UTC, Tasha-Ball commented on src/styles/style.css
> +    position: absolute;
изначально хотела реализовать через position, в конце забыла убрать

2021-04-30 09:47 UTC, Tasha-Ball commented on src/api/button.js
> +export class Button {
в файле page.js 1 класс в названием Button. Второй класс в отдельном файле, т.к. пыталась разбить на модули

2021-04-30 09:47 UTC, Tasha-Ball commented on src/api/main.js
> +  if (event.target == document.querySelector('.pop-up-cart')) {
Можно попробовать вначале отдельно получить доступ к pop-up-cart и затем сравнивать
const modul = document.querySelector('.pop-up-cart')
.....
if (event.target == modul) .........

2021-04-30 09:48 UTC, Tasha-Ball commented
Добрый день.
Спасибо за развернутую обратную связь)
Изначально все классы были разбиты по модулям и соединены в одном файле main.js, но выдавало ошибку по причине того, что не подключила webpack, babel и др., т.к. поняла, что по заданию нужно обойтись без них. Поэтому в итоговом варианте объединила все классы в одном файле page.js. При необходимости, могу сегодня подключить webpack, babel и все разбить по модулям.
Ксс не разбила по файлам, т.к. стилистика относится к одной странице, решила, что достаточно одного файла.

2021-04-30 11:55 UTC, idbolshakov commented on src/styles/style.css
> +    padding-left: calc(50% - 570px);
а почему выравнивание по центру решила делать через calc ? Почему более простые и наглядные способы не подошли?

2021-04-30 11:57 UTC, idbolshakov commented on src/api/button.js
> +export class Button {
в рамках одного проекта а тем более одной страницы не правильно делать классы с одинаковыми именами

2021-04-30 15:38 UTC, Tasha-Ball commented on src/styles/style.css
> +    padding-left: calc(50% - 570px);
Если брать container, то у него при уменьшении экрана, отступы начинают сжимать контент. В случае использования calc мы получаем динамические отступы, что даст нам фиксацию контента по центру, также не нужно создавать отдельный div

2021-04-30 15:44 UTC, Tasha-Ball commented on src/api/button.js
> +export class Button {
класс один, он отображается дублем по причине того, что моя попытка разбить на модули без бабеля провалилась. По сути в папке сейчас:
1. файл page.js, в котором собраны все классы (дублей нет), и этот файл подключен к html.
2. еще 7 файлов, в которых классы разбиты по модулям и собираются в одном файле main.js (также дублей нет) - они для дальнейшей сборки при подключении бабеля (build).

По факту дублей классов нет

2021-04-30 19:21 UTC, idbolshakov commented on src/styles/style.css
> +    padding-left: calc(50% - 570px);
очень многодельный способ какой-то)

вроде бы все эти проблемы flex'ами легко решаются

2021-04-30 19:23 UTC, idbolshakov commented on src/api/button.js
> +export class Button {
когда ты отправляешь решение, нужно убедиться что оно полностью готово, работает, код прибран и нет ничего лишнего. А просто накидать кучу файлов, половина из которых лишняя и не для чего не нужна - это очень плохо.

нужно было хотя-бы сопроводительный коммент написать.

в командной разработке важно не просто побыстро наверстать макет и сдать, нужно следить за чистотой кода, чтобы тебе и команде было легко такой код поддерживать и дорабатывать

2021-05-14 08:56 UTC, closed without merging