Finished test task from Egor Panov
idbolshakov/apress-frontend_test_task pull request #69
Opened 2021-04-29 07:07 UTC by veloni

2021-04-29 15:31 UTC, idbolshakov requested changes

2021-04-29 15:31 UTC, idbolshakov commented on src/clear.css
> +/* Указываем box sizing */
откуда этот файл и для чего здесь?

2021-04-29 15:31 UTC, idbolshakov commented on src/clear.css
> +    animation-duration: 0.01ms !important;
у тебя в решении не увидел ни одной анимации

2021-04-29 15:31 UTC, idbolshakov commented on src/index.css
> +h2 {
задание стилей напрямую к элементу - плохая практика, если речь не идет о нормализации стилей

2021-04-29 15:31 UTC, idbolshakov commented on src/index.css
> +  position: absolute;
зачем тут position absolute ?

2021-04-29 15:31 UTC, idbolshakov commented on src/scripts/listener.js
> +    const addSpacePrice = String(item.price).replace(/(\d)(?=(\d{3})+(\D|$))/g, '$1 ');
а для чего тут регулярное выражение?

2021-04-29 15:31 UTC, idbolshakov commented on src/scripts/listener.js
> +    productsWrapper.insertAdjacentHTML('beforeend',`
для 10 товаров у тебя будет вызывать 10 раз дорогая операция вставки значения в DOM. Как можно оптимизировать?

2021-04-29 15:31 UTC, idbolshakov commented on src/scripts/listener.js
> +          <button
у кнопки должен быть обязательный атрибут type

2021-04-29 15:31 UTC, idbolshakov commented on src/scripts/listener.js
> +const listener = () => {
очень странное название для файла. Чего он слушает?)

2021-04-29 15:31 UTC, idbolshakov commented on src/scripts/renderData.js
> +  buttonAddInOrder.forEach((item) => {
для 10 товаров будет 10 обработчиков события клик по кнопке заказа, для 100 товаров будет 100. Есть идеи как это можно оптимизировать?

2021-04-29 15:31 UTC, idbolshakov commented
Спасибо за выполнение ТЗ! К решению есть несколько вопросов)

2021-04-29 16:43 UTC, veloni commented on src/clear.css
> +/* Указываем box sizing */
Я добавил этот файл. Он убирает дефолтные отсупы у элементов, удаляет стандартную стилизацию элементов и прочее, что в свою очередь упрощает работу с вёрсткой.

2021-04-29 16:43 UTC, veloni commented on src/clear.css
> +    animation-duration: 0.01ms !important;
Мой косяк

2021-04-29 16:43 UTC, veloni commented on src/index.css
> +h2 {
Буду иметь ввиду

2021-04-29 16:45 UTC, veloni commented on src/index.css
> +  position: absolute;
Ставил исходя из позиционирования блоков на макете

2021-04-29 16:48 UTC, veloni commented on src/clear.css
> +/* Указываем box sizing */
Ой извинити, чёт не понял, взял файл из интернета где-то с пол года назад.

2021-04-29 16:52 UTC, veloni commented on src/scripts/listener.js
> +    const addSpacePrice = String(item.price).replace(/(\d)(?=(\d{3})+(\D|$))/g, '$1 ');
Добавляю пробелы в цене, после 3 символов

2021-04-29 18:37 UTC, idbolshakov commented on src/index.css
> +  position: absolute;
и все таки я не понял зачем position: absolute используется

2021-04-29 18:38 UTC, idbolshakov commented on src/scripts/listener.js
> +    const addSpacePrice = String(item.price).replace(/(\d)(?=(\d{3})+(\D|$))/g, '$1 ');
кажется, что через пол года взглянуть на эту регулярку и совсем грустно станет. Лучше их или не использовать или оставлять комментарии в коде что делает эта регулярка и зачем

2021-04-30 11:49 UTC, veloni commented on src/index.css
> +  position: absolute;
Да, уместней было использовать position:fixed, появится родительский элемент и всё слетит

2021-04-30 11:50 UTC, veloni commented on src/scripts/listener.js
> +    productsWrapper.insertAdjacentHTML('beforeend',`
Оптимизировал, все элементы сохраняются в одну строку и один раз вызываются в insertAdjacentHTML

2021-04-30 11:52 UTC, veloni commented on src/scripts/renderData.js
> +  buttonAddInOrder.forEach((item) => {
Переписал, сделал делегирование событий, про делегирование читал здесь [https://learn.javascript.ru/event-delegation](url)

2021-04-30 19:25 UTC, idbolshakov commented on src/index.css
> +  position: absolute;
а fixed для чего?))

2021-05-01 05:52 UTC, veloni commented on src/index.css
> +  position: absolute;
Position вообще не нужен, следовало через flex позиционировать по центру, данная компонента не должна была быть позиционирована относительно экрана, при добавлении новых компонент человек может не понять почему верстка летит. Меня смутил макет, пытался позиционировать чуть правее относительно центра.

2021-05-14 08:56 UTC, closed without merging