Comediant
idbolshakov/apress-frontend_test_task pull request #70
Opened 2021-05-05 11:47 UTC by Comediant24

## Добрый день!

#### Кратко о фичах:

- Для отрисовки карточек создан template элемент - так быстрее, такой код легче читать, легче поддерживать.
- На попапы повешены обработчики закрытия попапа: по клавише, по клику на оверлей.
- После закрытия попапа обработчик клавиши Esc удаляется.
- Файловая структура и верстка выполнена по БЭМ.
- Использованы семантические теги.
- Для Popup и Card сделаны классы и для их отрисовки используются соответствующие методы классов.
- Не использую модули так как по ТЗ нужно запускать без сервера.

2021-05-06 19:19 UTC, idbolshakov requested changes
Привет.  Спасибо за выполнение ТЗ. В общем и целом все круто. Видно что знаешь что такое БЭМ и для чего он, а также приятна общая тенденция к структуризации кода, при этом код не выглядит перегруженным.

Есть небольшие замечания:
- очень перегруженный файл со стилями блока popup, кажется что лучше разбить (сейчас этого делать не нужно)
- история с использованием `<template>` тега лично для меня выглядит не очень красиво, в будущем такой код будет сложно поддерживать. Редактирование шаблона выполнено в очень императивном стиле. Если нужно добавить какой-то динамически изменяемый атрибут в теге, тебе нужно сначала добавить его в html, потом внутри js кода написать строчку с редактированием этого атрибута.
- пустой класс `Product` зачем?
- по производительности вариант с навшиванием слушателей событий под каждый экземпляр класса `Card` очень плохой. С одной стороны ты хотел инкапсулировать всю логику работы  с карточкой товара внутрь класса, но фактически это решение приводит к просадкам производительности.  
- повторяющиеся цвета можно вынести в css переменные
- в файле popup.js три класса объявлены - не очень красиво

2021-05-06 19:19 UTC, idbolshakov commented on src/index.js
> +    handleBasketClick: () => {
для каждой карточки свои обработчики событий - неэффективно

2021-05-06 19:19 UTC, idbolshakov commented on src/index.js
> +  list.append(cardProduct.generateCard());
10 раз будет вызываться дорогая операция вставки элементов в DOM

2021-05-06 19:19 UTC, idbolshakov commented on src/utils/constants.js
> +var TEMPLATE_CARD = 'card-template';
объявление кучи переменных в глобальной области видимости - плохая практика

2021-05-11 23:54 UTC, Comediant24 commented
Вчера уже после подумал, что естественно я бы этот обработчик реализовал бы через делегирование.
В новых коммитах убрал обработчики с каждой карточки и пофиксил баг с оверлеем.

2021-05-11 23:55 UTC, Comediant24 commented on src/index.js
> +    handleBasketClick: () => {
да, решил это через делегирование.

2021-05-27 09:33 UTC, closed without merging