Completed test task
idbolshakov/apress-frontend_test_task pull request #71
Opened 2021-05-21 08:16 UTC by dkihada

Добрый день!

Что сделано:

- файл HTML - подключены файлы JS и CSS и добавлено два блока для rendera
- render данных, происходит из компонентов. Компоненты для удобства разбил на папки
- отрисовка popup в html происходит динамически, после  нажатия клавиш "Купить" / "Положить в корзину"
- index.css - использую как главный файл стилей с переменными
- данные взяты как указано в ТЗ, только из файла products.js

2021-05-24 06:39 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ. К решению есть несколько вопросов

1. Картинки непропорционально растягиваются
![image](https://user-images.githubusercontent.com/17525238/119306105-1e4c8100-bc83-11eb-846a-cc43c08f43f4.png)

2. Верстка попапа заказа поехала
![image](https://user-images.githubusercontent.com/17525238/119306141-2e646080-bc83-11eb-8c6c-4cb9fd8eaa02.png)


из приятного
1. здорово что используешь ксс переменные
2. более-менее удачная структуризация кода, только с ксс не совсем понятно то-ли БЭМ то-ли нет
3. рендер в js-e через innerHTML а не через createElement - очень хорошо

2021-05-24 06:39 UTC, idbolshakov commented on src/index.html
> +    <link rel="stylesheet" href="Components/Catalog/Catalog.css">
плохая практика вставлять link rel="stylesheet" в бади документа 
![image](https://user-images.githubusercontent.com/17525238/119306397-84390880-bc83-11eb-83b2-ffe12f7525b2.png)

2021-05-24 06:39 UTC, idbolshakov commented on src/Components/Catalog/Catalog.css
> +.catalog-item__img {
БЭМ селекторы используются вперемешку с обычными селекторами - только запутывает

2021-05-24 06:39 UTC, idbolshakov commented on src/Components/Popup-Card/Popup-Card.js
> +      for (let index = 0; index < API.products.length; index++) {
в одном файле используешь `forEach` в другом цикл `for` - не очень хорошо смешивать подходы

2021-05-24 06:39 UTC, idbolshakov commented on src/Components/Popup-Card/Popup-Card.js
> +         btnCard[index].addEventListener('click', (e) => {
для 10 товаров будет 10 обработчиков события, для 20 - 20 и тд

почитай про делегирование событий

2021-05-24 07:43 UTC, dkihada commented
Добрый день!

По БЭМ, понял, по поводу чего возникли вопросы - не корректно проставил элементы, в некоторых местах.

По верстка странно, что поехала, когда тестировал у себя, такого не было, проверю ещё раз.

Благодарю, за обратную связь!

2021-05-25 15:52 UTC, dkihada commented
Благодарю, за обратную связь!

Обращу внимание на все замечания и проработаю

2021-05-27 09:33 UTC, closed without merging