тестовое задание фронтенд Настя
idbolshakov/apress-frontend_test_task pull request #73
Opened 2021-09-20 16:30 UTC by rascal666

2021-09-21 09:50 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ. При попытке открыть index.html в браузере - ничего не происходит. В условиях задачи был пункт, что решение должно открываться просто в браузере без доп. сервисов. Сможешь поправить свой вариант так, чтобы все работало?

2021-09-21 09:56 UTC, idbolshakov requested changes

2021-09-21 09:56 UTC, idbolshakov commented on src/css/popap.css
> +	/* background-color: #9194ff; */
в решении, которое отправляешь на проверку не должно быть всякой грязи - закомментированные строчки кода - это грязь

2021-09-21 09:56 UTC, idbolshakov commented on src/css/popap.css
> +@keyframes anim {
очень непонятное название. Что за `anim` ? Что это анимация итак понятно, гораздо ценнее написать что именно делает эта твоя анимация

2021-09-21 09:56 UTC, idbolshakov commented on src/css/style.css
> +.btn2 {
именовать таким образом что-либо - очень плохая практика. Нужно давать понятные имена - что за кнопка, что делает. А не просто  кнопка-1, кнопка-2

2021-09-21 09:56 UTC, idbolshakov commented on src/css/style.css
> +.iconBasket__img {
зачем тут 2 подчеркивания? Это типо БЭМ у тебя?

2021-09-21 09:56 UTC, idbolshakov commented on src/index.html
> +<!-- @format -->
это что и зачем?

2021-09-21 09:56 UTC, idbolshakov commented on src/index.js
> +    async products() {
это что и зачем? У тебя по условию задачи уже все было доступно из глобальной области видимости. Не нужно придумывать и усложнять решение на ровно месте

2021-09-21 09:56 UTC, idbolshakov commented on src/index.js
> +const getProducts = async () => {
async await  ты тут приплела просто на ровном месте. Это тут совсем не требуется. Все дожно работать синхронно.

2021-09-21 09:56 UTC, idbolshakov commented on src/index.js
> +        _mainContent.onclick = e => {
для 10 товаров у тебя будет 10 обработчиков `onClick` для 100 - 100 и тд. 

Есть идеи как оптимизировать это?

2021-09-22 07:33 UTC, rascal666 commented on src/css/popap.css
> +	/* background-color: #9194ff; */
убрала

2021-09-22 07:33 UTC, rascal666 commented on src/css/popap.css
> +@keyframes anim {
поняла, переименовала

2021-09-22 07:34 UTC, rascal666 commented on src/css/style.css
> +.btn2 {
да, согласна. поправила

2021-09-22 07:34 UTC, rascal666 commented on src/css/style.css
> +.iconBasket__img {
да

2021-09-22 07:34 UTC, rascal666 commented on src/index.html
> +<!-- @format -->
расширение prettier автоматически добавляет

2021-09-22 07:36 UTC, rascal666 commented on src/index.js
> +    async products() {
async await убрала

2021-09-22 07:36 UTC, rascal666 commented on src/index.js
> +const getProducts = async () => {
async await убрала

2021-09-22 07:36 UTC, rascal666 commented on src/index.js
> +        _mainContent.onclick = e => {
_mainContent.onclick вынесла за пределы forEach и переписала логику

2021-09-27 05:24 UTC, idbolshakov commented
https://gist.github.com/idbolshakov/ae3aa30544176063e47819b07191f3aa список тем которые нужно прочитать и понять. После можно попробовать еще пообщаться. Пока рано.

2021-09-27 05:24 UTC, closed without merging