тестовое
idbolshakov/apress-frontend_test_task pull request #75
Opened 2021-09-27 18:10 UTC by MaksSemkin

2021-09-28 12:53 UTC, idbolshakov requested changes
привет, спасибо за выполнение ТЗ. К решению есть несколько вопросов.

1. Если на странице открыть попап с товаром несколько раз, то при нажатии на крестик (закрытие попапа) он не закрывается с первого раза

2021-09-28 12:57 UTC, idbolshakov requested changes

2021-09-28 12:57 UTC, idbolshakov commented on src/index.css
> +    /*display: block;*/
зачем оставил это в решении?

2021-09-28 12:57 UTC, idbolshakov commented on src/index.css
> +.wrap {
знакомы ли какие-то системы организации css кода? Почему решил сложить все стили в один файл?

2021-09-28 12:57 UTC, idbolshakov commented on src/index.js
> +            <button class="close" onClick = "closeCard()" style="position: absolute; right: 0px" >X</button>
инлайновое определение обработчиков событий - плохая практика

2021-09-28 12:57 UTC, idbolshakov commented on src/index.js
> +let inOrderButtons = document.querySelectorAll('.inOrder');
почему тут let  а не const или var ?

2021-09-28 12:57 UTC, idbolshakov commented on src/index.js
> +       const el = document.createElement('div')
тут используешь `createElement` ниже `inerHTML` почему бы и этот `div `  в `innerHTML` не засунуть?

2021-09-28 12:57 UTC, idbolshakov commented on src/index.js
> +    closeButtons.forEach((item)=>{item.addEventListener('click',closeCard)})
для 10 товаров у тебя будет 10 обработчиков, для 100 - 100 и тд. Есть идеи как оптимизировать?

2021-09-29 16:33 UTC, MaksSemkin commented on src/index.js
> +    closeButtons.forEach((item)=>{item.addEventListener('click',closeCard)})
Идея есть. Кинуть один обработчик на страницу, создать условие по таргету и уже ,исходя из условия, показывать окно корзины или заказа.

2021-09-29 18:54 UTC, MaksSemkin commented on src/index.css
> +    /*display: block;*/
исправил

2021-09-29 18:54 UTC, MaksSemkin commented on src/index.js
> +let inOrderButtons = document.querySelectorAll('.inOrder');
исправил

2021-10-08 05:07 UTC, closed without merging