Рихард Окманис
idbolshakov/apress-frontend_test_task pull request #77
Opened 2021-10-12 18:40 UTC by Unvares

2021-10-14 06:16 UTC, idbolshakov requested changes
Привет. Спасибо за выполнение ТЗ. К решению есть несколько вопросов:

1. почему решил иконку закрытия сделать через png ? Какие есть недостатки у такого решения?
2.

2021-10-14 06:16 UTC, idbolshakov commented on src/css/common.css
> +  font-family: 'Open Sans', sans-serif;
почему основной шрифт Open Sans? Какие могут быть проблемы?

2021-10-14 06:16 UTC, idbolshakov commented on src/css/common.css
> +  pointer-events: none;
это зачем?

2021-10-14 06:16 UTC, idbolshakov commented on src/css/popup.css
> +.popup {
очень монструозный по стилям компонент получился

2021-10-14 06:16 UTC, idbolshakov commented on src/scripts/product.js
> +    while(true) {
очень странная конструкция. ЧТо ты тут делаешь и зачем?)

2021-10-14 06:16 UTC, idbolshakov commented on src/scripts/product.js
> +    this.orderButton.addEventListener('click', () => {
у тебя для каждого продукта свои обработчики события по клику? 10  товаров - 20 событий, 100 товаров - 200 событий?

как можно оптимизировать?

2021-10-14 06:16 UTC, idbolshakov commented
В общем и целом решение норм. Код структурирован, больших косяков нет.

2021-10-15 13:18 UTC, Unvares commented on src/css/common.css
> +  font-family: 'Open Sans', sans-serif;
Open Sans – один из наиболее доступных sans-serif шрифтов.
Он не подключится, если не установлен на компьютере, но это решается подключением шрифта через @import или @font-face, а также подключением системного шрифта из того же семейства.

2021-10-15 13:20 UTC, Unvares commented on src/css/common.css
> +  pointer-events: none;
Это лишнее. Оно нужно для того, чтобы пользователь не мог перетягивать фоновую графику на сайте, но тут фоновой графики нет.

2021-10-15 13:31 UTC, Unvares commented on src/scripts/product.js
> +    while(true) {
Создаю переменную, которая хранит в себе массив из посимвольно разобранной цены. Я посчитал эффективным решение вытягивать по три последних значения массива (= 3 последних цифры стоимости) по итерациям, потому что такой код может преобразовывать любые положительные значения.
1234567 -> "1 234 567 руб."

2021-10-15 13:35 UTC, Unvares commented on src/scripts/product.js
> +    this.orderButton.addEventListener('click', () => {
Полагаю, повесить eventListener на весь листинг и отслеживать по какой кнопке было произведено нажатие через event.target

2021-11-23 07:25 UTC, closed without merging